// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

// AXILiteS
// 0x00 : reserved
// 0x04 : reserved
// 0x08 : reserved
// 0x0c : reserved
// 0x10 : Data signal of image_in
//        bit 31~0 - image_in[31:0] (Read/Write)
// 0x14 : reserved
// 0x18 : Data signal of image_out
//        bit 31~0 - image_out[31:0] (Read/Write)
// 0x1c : reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XBLUR_AXILITES_ADDR_IMAGE_IN_DATA  0x10
#define XBLUR_AXILITES_BITS_IMAGE_IN_DATA  32
#define XBLUR_AXILITES_ADDR_IMAGE_OUT_DATA 0x18
#define XBLUR_AXILITES_BITS_IMAGE_OUT_DATA 32

