// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#include "blur_Mat2AXIM.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic blur_Mat2AXIM::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic blur_Mat2AXIM::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<2> blur_Mat2AXIM::ap_ST_st1_fsm_0 = "1";
const sc_lv<2> blur_Mat2AXIM::ap_ST_st2_fsm_1 = "10";
const sc_lv<32> blur_Mat2AXIM::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> blur_Mat2AXIM::ap_const_lv1_1 = "1";
const sc_lv<1> blur_Mat2AXIM::ap_const_lv1_0 = "0";
const sc_lv<3> blur_Mat2AXIM::ap_const_lv3_0 = "000";
const sc_lv<2> blur_Mat2AXIM::ap_const_lv2_0 = "00";
const sc_lv<4> blur_Mat2AXIM::ap_const_lv4_0 = "0000";
const sc_lv<32> blur_Mat2AXIM::ap_const_lv32_1 = "1";
const sc_lv<8> blur_Mat2AXIM::ap_const_lv8_0 = "00000000";

blur_Mat2AXIM::blur_Mat2AXIM(sc_module_name name) : sc_module(name), mVcdFile(0) {
    grp_blur_Mat2Array_fu_34 = new blur_Mat2Array("grp_blur_Mat2Array_fu_34");
    grp_blur_Mat2Array_fu_34->ap_clk(ap_clk);
    grp_blur_Mat2Array_fu_34->ap_rst(ap_rst);
    grp_blur_Mat2Array_fu_34->ap_start(grp_blur_Mat2Array_fu_34_ap_start);
    grp_blur_Mat2Array_fu_34->ap_done(grp_blur_Mat2Array_fu_34_ap_done);
    grp_blur_Mat2Array_fu_34->ap_idle(grp_blur_Mat2Array_fu_34_ap_idle);
    grp_blur_Mat2Array_fu_34->ap_ready(grp_blur_Mat2Array_fu_34_ap_ready);
    grp_blur_Mat2Array_fu_34->img_data_stream_V_dout(grp_blur_Mat2Array_fu_34_img_data_stream_V_dout);
    grp_blur_Mat2Array_fu_34->img_data_stream_V_empty_n(grp_blur_Mat2Array_fu_34_img_data_stream_V_empty_n);
    grp_blur_Mat2Array_fu_34->img_data_stream_V_read(grp_blur_Mat2Array_fu_34_img_data_stream_V_read);
    grp_blur_Mat2Array_fu_34->m_axi_fb_AWVALID(grp_blur_Mat2Array_fu_34_m_axi_fb_AWVALID);
    grp_blur_Mat2Array_fu_34->m_axi_fb_AWREADY(grp_blur_Mat2Array_fu_34_m_axi_fb_AWREADY);
    grp_blur_Mat2Array_fu_34->m_axi_fb_AWADDR(grp_blur_Mat2Array_fu_34_m_axi_fb_AWADDR);
    grp_blur_Mat2Array_fu_34->m_axi_fb_AWID(grp_blur_Mat2Array_fu_34_m_axi_fb_AWID);
    grp_blur_Mat2Array_fu_34->m_axi_fb_AWLEN(grp_blur_Mat2Array_fu_34_m_axi_fb_AWLEN);
    grp_blur_Mat2Array_fu_34->m_axi_fb_AWSIZE(grp_blur_Mat2Array_fu_34_m_axi_fb_AWSIZE);
    grp_blur_Mat2Array_fu_34->m_axi_fb_AWBURST(grp_blur_Mat2Array_fu_34_m_axi_fb_AWBURST);
    grp_blur_Mat2Array_fu_34->m_axi_fb_AWLOCK(grp_blur_Mat2Array_fu_34_m_axi_fb_AWLOCK);
    grp_blur_Mat2Array_fu_34->m_axi_fb_AWCACHE(grp_blur_Mat2Array_fu_34_m_axi_fb_AWCACHE);
    grp_blur_Mat2Array_fu_34->m_axi_fb_AWPROT(grp_blur_Mat2Array_fu_34_m_axi_fb_AWPROT);
    grp_blur_Mat2Array_fu_34->m_axi_fb_AWQOS(grp_blur_Mat2Array_fu_34_m_axi_fb_AWQOS);
    grp_blur_Mat2Array_fu_34->m_axi_fb_AWREGION(grp_blur_Mat2Array_fu_34_m_axi_fb_AWREGION);
    grp_blur_Mat2Array_fu_34->m_axi_fb_AWUSER(grp_blur_Mat2Array_fu_34_m_axi_fb_AWUSER);
    grp_blur_Mat2Array_fu_34->m_axi_fb_WVALID(grp_blur_Mat2Array_fu_34_m_axi_fb_WVALID);
    grp_blur_Mat2Array_fu_34->m_axi_fb_WREADY(grp_blur_Mat2Array_fu_34_m_axi_fb_WREADY);
    grp_blur_Mat2Array_fu_34->m_axi_fb_WDATA(grp_blur_Mat2Array_fu_34_m_axi_fb_WDATA);
    grp_blur_Mat2Array_fu_34->m_axi_fb_WSTRB(grp_blur_Mat2Array_fu_34_m_axi_fb_WSTRB);
    grp_blur_Mat2Array_fu_34->m_axi_fb_WLAST(grp_blur_Mat2Array_fu_34_m_axi_fb_WLAST);
    grp_blur_Mat2Array_fu_34->m_axi_fb_WID(grp_blur_Mat2Array_fu_34_m_axi_fb_WID);
    grp_blur_Mat2Array_fu_34->m_axi_fb_WUSER(grp_blur_Mat2Array_fu_34_m_axi_fb_WUSER);
    grp_blur_Mat2Array_fu_34->m_axi_fb_ARVALID(grp_blur_Mat2Array_fu_34_m_axi_fb_ARVALID);
    grp_blur_Mat2Array_fu_34->m_axi_fb_ARREADY(grp_blur_Mat2Array_fu_34_m_axi_fb_ARREADY);
    grp_blur_Mat2Array_fu_34->m_axi_fb_ARADDR(grp_blur_Mat2Array_fu_34_m_axi_fb_ARADDR);
    grp_blur_Mat2Array_fu_34->m_axi_fb_ARID(grp_blur_Mat2Array_fu_34_m_axi_fb_ARID);
    grp_blur_Mat2Array_fu_34->m_axi_fb_ARLEN(grp_blur_Mat2Array_fu_34_m_axi_fb_ARLEN);
    grp_blur_Mat2Array_fu_34->m_axi_fb_ARSIZE(grp_blur_Mat2Array_fu_34_m_axi_fb_ARSIZE);
    grp_blur_Mat2Array_fu_34->m_axi_fb_ARBURST(grp_blur_Mat2Array_fu_34_m_axi_fb_ARBURST);
    grp_blur_Mat2Array_fu_34->m_axi_fb_ARLOCK(grp_blur_Mat2Array_fu_34_m_axi_fb_ARLOCK);
    grp_blur_Mat2Array_fu_34->m_axi_fb_ARCACHE(grp_blur_Mat2Array_fu_34_m_axi_fb_ARCACHE);
    grp_blur_Mat2Array_fu_34->m_axi_fb_ARPROT(grp_blur_Mat2Array_fu_34_m_axi_fb_ARPROT);
    grp_blur_Mat2Array_fu_34->m_axi_fb_ARQOS(grp_blur_Mat2Array_fu_34_m_axi_fb_ARQOS);
    grp_blur_Mat2Array_fu_34->m_axi_fb_ARREGION(grp_blur_Mat2Array_fu_34_m_axi_fb_ARREGION);
    grp_blur_Mat2Array_fu_34->m_axi_fb_ARUSER(grp_blur_Mat2Array_fu_34_m_axi_fb_ARUSER);
    grp_blur_Mat2Array_fu_34->m_axi_fb_RVALID(grp_blur_Mat2Array_fu_34_m_axi_fb_RVALID);
    grp_blur_Mat2Array_fu_34->m_axi_fb_RREADY(grp_blur_Mat2Array_fu_34_m_axi_fb_RREADY);
    grp_blur_Mat2Array_fu_34->m_axi_fb_RDATA(grp_blur_Mat2Array_fu_34_m_axi_fb_RDATA);
    grp_blur_Mat2Array_fu_34->m_axi_fb_RLAST(grp_blur_Mat2Array_fu_34_m_axi_fb_RLAST);
    grp_blur_Mat2Array_fu_34->m_axi_fb_RID(grp_blur_Mat2Array_fu_34_m_axi_fb_RID);
    grp_blur_Mat2Array_fu_34->m_axi_fb_RUSER(grp_blur_Mat2Array_fu_34_m_axi_fb_RUSER);
    grp_blur_Mat2Array_fu_34->m_axi_fb_RRESP(grp_blur_Mat2Array_fu_34_m_axi_fb_RRESP);
    grp_blur_Mat2Array_fu_34->m_axi_fb_BVALID(grp_blur_Mat2Array_fu_34_m_axi_fb_BVALID);
    grp_blur_Mat2Array_fu_34->m_axi_fb_BREADY(grp_blur_Mat2Array_fu_34_m_axi_fb_BREADY);
    grp_blur_Mat2Array_fu_34->m_axi_fb_BRESP(grp_blur_Mat2Array_fu_34_m_axi_fb_BRESP);
    grp_blur_Mat2Array_fu_34->m_axi_fb_BID(grp_blur_Mat2Array_fu_34_m_axi_fb_BID);
    grp_blur_Mat2Array_fu_34->m_axi_fb_BUSER(grp_blur_Mat2Array_fu_34_m_axi_fb_BUSER);
    grp_blur_Mat2Array_fu_34->image_out1(grp_blur_Mat2Array_fu_34_image_out1);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( grp_blur_Mat2Array_fu_34_ap_done );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( grp_blur_Mat2Array_fu_34_ap_done );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_ap_sig_bdd_163);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_21);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_98);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( image_out_empty_n );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_bdd_21 );

    SC_METHOD(thread_ap_sig_cseq_ST_st2_fsm_1);
    sensitive << ( ap_sig_bdd_163 );

    SC_METHOD(thread_grp_blur_Mat2Array_fu_34_ap_start);
    sensitive << ( grp_blur_Mat2Array_fu_34_ap_start_ap_start_reg );

    SC_METHOD(thread_grp_blur_Mat2Array_fu_34_image_out1);
    sensitive << ( image_out_read_reg_44 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_blur_Mat2Array_fu_34_img_data_stream_V_dout);
    sensitive << ( img_data_stream_V_dout );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_blur_Mat2Array_fu_34_img_data_stream_V_empty_n);
    sensitive << ( img_data_stream_V_empty_n );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_blur_Mat2Array_fu_34_m_axi_fb_ARREADY);

    SC_METHOD(thread_grp_blur_Mat2Array_fu_34_m_axi_fb_AWREADY);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( m_axi_fb_AWREADY );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_blur_Mat2Array_fu_34_m_axi_fb_BID);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( m_axi_fb_BID );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_blur_Mat2Array_fu_34_m_axi_fb_BRESP);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( m_axi_fb_BRESP );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_blur_Mat2Array_fu_34_m_axi_fb_BUSER);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( m_axi_fb_BUSER );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_blur_Mat2Array_fu_34_m_axi_fb_BVALID);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( m_axi_fb_BVALID );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_blur_Mat2Array_fu_34_m_axi_fb_RDATA);

    SC_METHOD(thread_grp_blur_Mat2Array_fu_34_m_axi_fb_RID);

    SC_METHOD(thread_grp_blur_Mat2Array_fu_34_m_axi_fb_RLAST);

    SC_METHOD(thread_grp_blur_Mat2Array_fu_34_m_axi_fb_RRESP);

    SC_METHOD(thread_grp_blur_Mat2Array_fu_34_m_axi_fb_RUSER);

    SC_METHOD(thread_grp_blur_Mat2Array_fu_34_m_axi_fb_RVALID);

    SC_METHOD(thread_grp_blur_Mat2Array_fu_34_m_axi_fb_WREADY);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( m_axi_fb_WREADY );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_image_out_read);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_sig_bdd_98 );

    SC_METHOD(thread_img_data_stream_V_read);
    sensitive << ( grp_blur_Mat2Array_fu_34_img_data_stream_V_read );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_m_axi_fb_ARADDR);

    SC_METHOD(thread_m_axi_fb_ARBURST);

    SC_METHOD(thread_m_axi_fb_ARCACHE);

    SC_METHOD(thread_m_axi_fb_ARID);

    SC_METHOD(thread_m_axi_fb_ARLEN);

    SC_METHOD(thread_m_axi_fb_ARLOCK);

    SC_METHOD(thread_m_axi_fb_ARPROT);

    SC_METHOD(thread_m_axi_fb_ARQOS);

    SC_METHOD(thread_m_axi_fb_ARREGION);

    SC_METHOD(thread_m_axi_fb_ARSIZE);

    SC_METHOD(thread_m_axi_fb_ARUSER);

    SC_METHOD(thread_m_axi_fb_ARVALID);

    SC_METHOD(thread_m_axi_fb_AWADDR);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( grp_blur_Mat2Array_fu_34_m_axi_fb_AWADDR );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_m_axi_fb_AWBURST);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( grp_blur_Mat2Array_fu_34_m_axi_fb_AWBURST );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_m_axi_fb_AWCACHE);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( grp_blur_Mat2Array_fu_34_m_axi_fb_AWCACHE );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_m_axi_fb_AWID);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( grp_blur_Mat2Array_fu_34_m_axi_fb_AWID );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_m_axi_fb_AWLEN);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( grp_blur_Mat2Array_fu_34_m_axi_fb_AWLEN );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_m_axi_fb_AWLOCK);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( grp_blur_Mat2Array_fu_34_m_axi_fb_AWLOCK );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_m_axi_fb_AWPROT);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( grp_blur_Mat2Array_fu_34_m_axi_fb_AWPROT );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_m_axi_fb_AWQOS);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( grp_blur_Mat2Array_fu_34_m_axi_fb_AWQOS );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_m_axi_fb_AWREGION);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( grp_blur_Mat2Array_fu_34_m_axi_fb_AWREGION );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_m_axi_fb_AWSIZE);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( grp_blur_Mat2Array_fu_34_m_axi_fb_AWSIZE );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_m_axi_fb_AWUSER);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( grp_blur_Mat2Array_fu_34_m_axi_fb_AWUSER );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_m_axi_fb_AWVALID);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( grp_blur_Mat2Array_fu_34_m_axi_fb_AWVALID );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_m_axi_fb_BREADY);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( grp_blur_Mat2Array_fu_34_m_axi_fb_BREADY );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_m_axi_fb_RREADY);

    SC_METHOD(thread_m_axi_fb_WDATA);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( grp_blur_Mat2Array_fu_34_m_axi_fb_WDATA );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_m_axi_fb_WID);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( grp_blur_Mat2Array_fu_34_m_axi_fb_WID );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_m_axi_fb_WLAST);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( grp_blur_Mat2Array_fu_34_m_axi_fb_WLAST );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_m_axi_fb_WSTRB);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( grp_blur_Mat2Array_fu_34_m_axi_fb_WSTRB );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_m_axi_fb_WUSER);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( grp_blur_Mat2Array_fu_34_m_axi_fb_WUSER );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_m_axi_fb_WVALID);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( grp_blur_Mat2Array_fu_34_m_axi_fb_WVALID );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_sig_bdd_98 );
    sensitive << ( grp_blur_Mat2Array_fu_34_ap_done );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "01";
    grp_blur_Mat2Array_fu_34_ap_start_ap_start_reg = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "blur_Mat2AXIM_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, img_data_stream_V_dout, "(port)img_data_stream_V_dout");
    sc_trace(mVcdFile, img_data_stream_V_empty_n, "(port)img_data_stream_V_empty_n");
    sc_trace(mVcdFile, img_data_stream_V_read, "(port)img_data_stream_V_read");
    sc_trace(mVcdFile, m_axi_fb_AWVALID, "(port)m_axi_fb_AWVALID");
    sc_trace(mVcdFile, m_axi_fb_AWREADY, "(port)m_axi_fb_AWREADY");
    sc_trace(mVcdFile, m_axi_fb_AWADDR, "(port)m_axi_fb_AWADDR");
    sc_trace(mVcdFile, m_axi_fb_AWID, "(port)m_axi_fb_AWID");
    sc_trace(mVcdFile, m_axi_fb_AWLEN, "(port)m_axi_fb_AWLEN");
    sc_trace(mVcdFile, m_axi_fb_AWSIZE, "(port)m_axi_fb_AWSIZE");
    sc_trace(mVcdFile, m_axi_fb_AWBURST, "(port)m_axi_fb_AWBURST");
    sc_trace(mVcdFile, m_axi_fb_AWLOCK, "(port)m_axi_fb_AWLOCK");
    sc_trace(mVcdFile, m_axi_fb_AWCACHE, "(port)m_axi_fb_AWCACHE");
    sc_trace(mVcdFile, m_axi_fb_AWPROT, "(port)m_axi_fb_AWPROT");
    sc_trace(mVcdFile, m_axi_fb_AWQOS, "(port)m_axi_fb_AWQOS");
    sc_trace(mVcdFile, m_axi_fb_AWREGION, "(port)m_axi_fb_AWREGION");
    sc_trace(mVcdFile, m_axi_fb_AWUSER, "(port)m_axi_fb_AWUSER");
    sc_trace(mVcdFile, m_axi_fb_WVALID, "(port)m_axi_fb_WVALID");
    sc_trace(mVcdFile, m_axi_fb_WREADY, "(port)m_axi_fb_WREADY");
    sc_trace(mVcdFile, m_axi_fb_WDATA, "(port)m_axi_fb_WDATA");
    sc_trace(mVcdFile, m_axi_fb_WSTRB, "(port)m_axi_fb_WSTRB");
    sc_trace(mVcdFile, m_axi_fb_WLAST, "(port)m_axi_fb_WLAST");
    sc_trace(mVcdFile, m_axi_fb_WID, "(port)m_axi_fb_WID");
    sc_trace(mVcdFile, m_axi_fb_WUSER, "(port)m_axi_fb_WUSER");
    sc_trace(mVcdFile, m_axi_fb_ARVALID, "(port)m_axi_fb_ARVALID");
    sc_trace(mVcdFile, m_axi_fb_ARREADY, "(port)m_axi_fb_ARREADY");
    sc_trace(mVcdFile, m_axi_fb_ARADDR, "(port)m_axi_fb_ARADDR");
    sc_trace(mVcdFile, m_axi_fb_ARID, "(port)m_axi_fb_ARID");
    sc_trace(mVcdFile, m_axi_fb_ARLEN, "(port)m_axi_fb_ARLEN");
    sc_trace(mVcdFile, m_axi_fb_ARSIZE, "(port)m_axi_fb_ARSIZE");
    sc_trace(mVcdFile, m_axi_fb_ARBURST, "(port)m_axi_fb_ARBURST");
    sc_trace(mVcdFile, m_axi_fb_ARLOCK, "(port)m_axi_fb_ARLOCK");
    sc_trace(mVcdFile, m_axi_fb_ARCACHE, "(port)m_axi_fb_ARCACHE");
    sc_trace(mVcdFile, m_axi_fb_ARPROT, "(port)m_axi_fb_ARPROT");
    sc_trace(mVcdFile, m_axi_fb_ARQOS, "(port)m_axi_fb_ARQOS");
    sc_trace(mVcdFile, m_axi_fb_ARREGION, "(port)m_axi_fb_ARREGION");
    sc_trace(mVcdFile, m_axi_fb_ARUSER, "(port)m_axi_fb_ARUSER");
    sc_trace(mVcdFile, m_axi_fb_RVALID, "(port)m_axi_fb_RVALID");
    sc_trace(mVcdFile, m_axi_fb_RREADY, "(port)m_axi_fb_RREADY");
    sc_trace(mVcdFile, m_axi_fb_RDATA, "(port)m_axi_fb_RDATA");
    sc_trace(mVcdFile, m_axi_fb_RLAST, "(port)m_axi_fb_RLAST");
    sc_trace(mVcdFile, m_axi_fb_RID, "(port)m_axi_fb_RID");
    sc_trace(mVcdFile, m_axi_fb_RUSER, "(port)m_axi_fb_RUSER");
    sc_trace(mVcdFile, m_axi_fb_RRESP, "(port)m_axi_fb_RRESP");
    sc_trace(mVcdFile, m_axi_fb_BVALID, "(port)m_axi_fb_BVALID");
    sc_trace(mVcdFile, m_axi_fb_BREADY, "(port)m_axi_fb_BREADY");
    sc_trace(mVcdFile, m_axi_fb_BRESP, "(port)m_axi_fb_BRESP");
    sc_trace(mVcdFile, m_axi_fb_BID, "(port)m_axi_fb_BID");
    sc_trace(mVcdFile, m_axi_fb_BUSER, "(port)m_axi_fb_BUSER");
    sc_trace(mVcdFile, image_out_dout, "(port)image_out_dout");
    sc_trace(mVcdFile, image_out_empty_n, "(port)image_out_empty_n");
    sc_trace(mVcdFile, image_out_read, "(port)image_out_read");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_bdd_21, "ap_sig_bdd_21");
    sc_trace(mVcdFile, image_out_read_reg_44, "image_out_read_reg_44");
    sc_trace(mVcdFile, ap_sig_bdd_98, "ap_sig_bdd_98");
    sc_trace(mVcdFile, grp_blur_Mat2Array_fu_34_ap_start, "grp_blur_Mat2Array_fu_34_ap_start");
    sc_trace(mVcdFile, grp_blur_Mat2Array_fu_34_ap_done, "grp_blur_Mat2Array_fu_34_ap_done");
    sc_trace(mVcdFile, grp_blur_Mat2Array_fu_34_ap_idle, "grp_blur_Mat2Array_fu_34_ap_idle");
    sc_trace(mVcdFile, grp_blur_Mat2Array_fu_34_ap_ready, "grp_blur_Mat2Array_fu_34_ap_ready");
    sc_trace(mVcdFile, grp_blur_Mat2Array_fu_34_img_data_stream_V_dout, "grp_blur_Mat2Array_fu_34_img_data_stream_V_dout");
    sc_trace(mVcdFile, grp_blur_Mat2Array_fu_34_img_data_stream_V_empty_n, "grp_blur_Mat2Array_fu_34_img_data_stream_V_empty_n");
    sc_trace(mVcdFile, grp_blur_Mat2Array_fu_34_img_data_stream_V_read, "grp_blur_Mat2Array_fu_34_img_data_stream_V_read");
    sc_trace(mVcdFile, grp_blur_Mat2Array_fu_34_m_axi_fb_AWVALID, "grp_blur_Mat2Array_fu_34_m_axi_fb_AWVALID");
    sc_trace(mVcdFile, grp_blur_Mat2Array_fu_34_m_axi_fb_AWREADY, "grp_blur_Mat2Array_fu_34_m_axi_fb_AWREADY");
    sc_trace(mVcdFile, grp_blur_Mat2Array_fu_34_m_axi_fb_AWADDR, "grp_blur_Mat2Array_fu_34_m_axi_fb_AWADDR");
    sc_trace(mVcdFile, grp_blur_Mat2Array_fu_34_m_axi_fb_AWID, "grp_blur_Mat2Array_fu_34_m_axi_fb_AWID");
    sc_trace(mVcdFile, grp_blur_Mat2Array_fu_34_m_axi_fb_AWLEN, "grp_blur_Mat2Array_fu_34_m_axi_fb_AWLEN");
    sc_trace(mVcdFile, grp_blur_Mat2Array_fu_34_m_axi_fb_AWSIZE, "grp_blur_Mat2Array_fu_34_m_axi_fb_AWSIZE");
    sc_trace(mVcdFile, grp_blur_Mat2Array_fu_34_m_axi_fb_AWBURST, "grp_blur_Mat2Array_fu_34_m_axi_fb_AWBURST");
    sc_trace(mVcdFile, grp_blur_Mat2Array_fu_34_m_axi_fb_AWLOCK, "grp_blur_Mat2Array_fu_34_m_axi_fb_AWLOCK");
    sc_trace(mVcdFile, grp_blur_Mat2Array_fu_34_m_axi_fb_AWCACHE, "grp_blur_Mat2Array_fu_34_m_axi_fb_AWCACHE");
    sc_trace(mVcdFile, grp_blur_Mat2Array_fu_34_m_axi_fb_AWPROT, "grp_blur_Mat2Array_fu_34_m_axi_fb_AWPROT");
    sc_trace(mVcdFile, grp_blur_Mat2Array_fu_34_m_axi_fb_AWQOS, "grp_blur_Mat2Array_fu_34_m_axi_fb_AWQOS");
    sc_trace(mVcdFile, grp_blur_Mat2Array_fu_34_m_axi_fb_AWREGION, "grp_blur_Mat2Array_fu_34_m_axi_fb_AWREGION");
    sc_trace(mVcdFile, grp_blur_Mat2Array_fu_34_m_axi_fb_AWUSER, "grp_blur_Mat2Array_fu_34_m_axi_fb_AWUSER");
    sc_trace(mVcdFile, grp_blur_Mat2Array_fu_34_m_axi_fb_WVALID, "grp_blur_Mat2Array_fu_34_m_axi_fb_WVALID");
    sc_trace(mVcdFile, grp_blur_Mat2Array_fu_34_m_axi_fb_WREADY, "grp_blur_Mat2Array_fu_34_m_axi_fb_WREADY");
    sc_trace(mVcdFile, grp_blur_Mat2Array_fu_34_m_axi_fb_WDATA, "grp_blur_Mat2Array_fu_34_m_axi_fb_WDATA");
    sc_trace(mVcdFile, grp_blur_Mat2Array_fu_34_m_axi_fb_WSTRB, "grp_blur_Mat2Array_fu_34_m_axi_fb_WSTRB");
    sc_trace(mVcdFile, grp_blur_Mat2Array_fu_34_m_axi_fb_WLAST, "grp_blur_Mat2Array_fu_34_m_axi_fb_WLAST");
    sc_trace(mVcdFile, grp_blur_Mat2Array_fu_34_m_axi_fb_WID, "grp_blur_Mat2Array_fu_34_m_axi_fb_WID");
    sc_trace(mVcdFile, grp_blur_Mat2Array_fu_34_m_axi_fb_WUSER, "grp_blur_Mat2Array_fu_34_m_axi_fb_WUSER");
    sc_trace(mVcdFile, grp_blur_Mat2Array_fu_34_m_axi_fb_ARVALID, "grp_blur_Mat2Array_fu_34_m_axi_fb_ARVALID");
    sc_trace(mVcdFile, grp_blur_Mat2Array_fu_34_m_axi_fb_ARREADY, "grp_blur_Mat2Array_fu_34_m_axi_fb_ARREADY");
    sc_trace(mVcdFile, grp_blur_Mat2Array_fu_34_m_axi_fb_ARADDR, "grp_blur_Mat2Array_fu_34_m_axi_fb_ARADDR");
    sc_trace(mVcdFile, grp_blur_Mat2Array_fu_34_m_axi_fb_ARID, "grp_blur_Mat2Array_fu_34_m_axi_fb_ARID");
    sc_trace(mVcdFile, grp_blur_Mat2Array_fu_34_m_axi_fb_ARLEN, "grp_blur_Mat2Array_fu_34_m_axi_fb_ARLEN");
    sc_trace(mVcdFile, grp_blur_Mat2Array_fu_34_m_axi_fb_ARSIZE, "grp_blur_Mat2Array_fu_34_m_axi_fb_ARSIZE");
    sc_trace(mVcdFile, grp_blur_Mat2Array_fu_34_m_axi_fb_ARBURST, "grp_blur_Mat2Array_fu_34_m_axi_fb_ARBURST");
    sc_trace(mVcdFile, grp_blur_Mat2Array_fu_34_m_axi_fb_ARLOCK, "grp_blur_Mat2Array_fu_34_m_axi_fb_ARLOCK");
    sc_trace(mVcdFile, grp_blur_Mat2Array_fu_34_m_axi_fb_ARCACHE, "grp_blur_Mat2Array_fu_34_m_axi_fb_ARCACHE");
    sc_trace(mVcdFile, grp_blur_Mat2Array_fu_34_m_axi_fb_ARPROT, "grp_blur_Mat2Array_fu_34_m_axi_fb_ARPROT");
    sc_trace(mVcdFile, grp_blur_Mat2Array_fu_34_m_axi_fb_ARQOS, "grp_blur_Mat2Array_fu_34_m_axi_fb_ARQOS");
    sc_trace(mVcdFile, grp_blur_Mat2Array_fu_34_m_axi_fb_ARREGION, "grp_blur_Mat2Array_fu_34_m_axi_fb_ARREGION");
    sc_trace(mVcdFile, grp_blur_Mat2Array_fu_34_m_axi_fb_ARUSER, "grp_blur_Mat2Array_fu_34_m_axi_fb_ARUSER");
    sc_trace(mVcdFile, grp_blur_Mat2Array_fu_34_m_axi_fb_RVALID, "grp_blur_Mat2Array_fu_34_m_axi_fb_RVALID");
    sc_trace(mVcdFile, grp_blur_Mat2Array_fu_34_m_axi_fb_RREADY, "grp_blur_Mat2Array_fu_34_m_axi_fb_RREADY");
    sc_trace(mVcdFile, grp_blur_Mat2Array_fu_34_m_axi_fb_RDATA, "grp_blur_Mat2Array_fu_34_m_axi_fb_RDATA");
    sc_trace(mVcdFile, grp_blur_Mat2Array_fu_34_m_axi_fb_RLAST, "grp_blur_Mat2Array_fu_34_m_axi_fb_RLAST");
    sc_trace(mVcdFile, grp_blur_Mat2Array_fu_34_m_axi_fb_RID, "grp_blur_Mat2Array_fu_34_m_axi_fb_RID");
    sc_trace(mVcdFile, grp_blur_Mat2Array_fu_34_m_axi_fb_RUSER, "grp_blur_Mat2Array_fu_34_m_axi_fb_RUSER");
    sc_trace(mVcdFile, grp_blur_Mat2Array_fu_34_m_axi_fb_RRESP, "grp_blur_Mat2Array_fu_34_m_axi_fb_RRESP");
    sc_trace(mVcdFile, grp_blur_Mat2Array_fu_34_m_axi_fb_BVALID, "grp_blur_Mat2Array_fu_34_m_axi_fb_BVALID");
    sc_trace(mVcdFile, grp_blur_Mat2Array_fu_34_m_axi_fb_BREADY, "grp_blur_Mat2Array_fu_34_m_axi_fb_BREADY");
    sc_trace(mVcdFile, grp_blur_Mat2Array_fu_34_m_axi_fb_BRESP, "grp_blur_Mat2Array_fu_34_m_axi_fb_BRESP");
    sc_trace(mVcdFile, grp_blur_Mat2Array_fu_34_m_axi_fb_BID, "grp_blur_Mat2Array_fu_34_m_axi_fb_BID");
    sc_trace(mVcdFile, grp_blur_Mat2Array_fu_34_m_axi_fb_BUSER, "grp_blur_Mat2Array_fu_34_m_axi_fb_BUSER");
    sc_trace(mVcdFile, grp_blur_Mat2Array_fu_34_image_out1, "grp_blur_Mat2Array_fu_34_image_out1");
    sc_trace(mVcdFile, grp_blur_Mat2Array_fu_34_ap_start_ap_start_reg, "grp_blur_Mat2Array_fu_34_ap_start_ap_start_reg");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st2_fsm_1, "ap_sig_cseq_ST_st2_fsm_1");
    sc_trace(mVcdFile, ap_sig_bdd_163, "ap_sig_bdd_163");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

blur_Mat2AXIM::~blur_Mat2AXIM() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete grp_blur_Mat2Array_fu_34;
}

void blur_Mat2AXIM::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                    !esl_seteq<1,1,1>(ap_const_logic_0, grp_blur_Mat2Array_fu_34_ap_done.read()))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_blur_Mat2Array_fu_34_ap_start_ap_start_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
             !ap_sig_bdd_98.read())) {
            grp_blur_Mat2Array_fu_34_ap_start_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_blur_Mat2Array_fu_34_ap_ready.read())) {
            grp_blur_Mat2Array_fu_34_ap_start_ap_start_reg = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && !ap_sig_bdd_98.read())) {
        image_out_read_reg_44 = image_out_dout.read();
    }
}

void blur_Mat2AXIM::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_done_reg.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
          !esl_seteq<1,1,1>(ap_const_logic_0, grp_blur_Mat2Array_fu_34_ap_done.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void blur_Mat2AXIM::thread_ap_idle() {
    if ((!esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void blur_Mat2AXIM::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         !esl_seteq<1,1,1>(ap_const_logic_0, grp_blur_Mat2Array_fu_34_ap_done.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void blur_Mat2AXIM::thread_ap_sig_bdd_163() {
    ap_sig_bdd_163 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void blur_Mat2AXIM::thread_ap_sig_bdd_21() {
    ap_sig_bdd_21 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void blur_Mat2AXIM::thread_ap_sig_bdd_98() {
    ap_sig_bdd_98 = (esl_seteq<1,1,1>(image_out_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void blur_Mat2AXIM::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_bdd_21.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void blur_Mat2AXIM::thread_ap_sig_cseq_ST_st2_fsm_1() {
    if (ap_sig_bdd_163.read()) {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    }
}

void blur_Mat2AXIM::thread_grp_blur_Mat2Array_fu_34_ap_start() {
    grp_blur_Mat2Array_fu_34_ap_start = grp_blur_Mat2Array_fu_34_ap_start_ap_start_reg.read();
}

void blur_Mat2AXIM::thread_grp_blur_Mat2Array_fu_34_image_out1() {
    grp_blur_Mat2Array_fu_34_image_out1 = image_out_read_reg_44.read();
}

void blur_Mat2AXIM::thread_grp_blur_Mat2Array_fu_34_img_data_stream_V_dout() {
    grp_blur_Mat2Array_fu_34_img_data_stream_V_dout = img_data_stream_V_dout.read();
}

void blur_Mat2AXIM::thread_grp_blur_Mat2Array_fu_34_img_data_stream_V_empty_n() {
    grp_blur_Mat2Array_fu_34_img_data_stream_V_empty_n = img_data_stream_V_empty_n.read();
}

void blur_Mat2AXIM::thread_grp_blur_Mat2Array_fu_34_m_axi_fb_ARREADY() {
    grp_blur_Mat2Array_fu_34_m_axi_fb_ARREADY = ap_const_logic_0;
}

void blur_Mat2AXIM::thread_grp_blur_Mat2Array_fu_34_m_axi_fb_AWREADY() {
    grp_blur_Mat2Array_fu_34_m_axi_fb_AWREADY = m_axi_fb_AWREADY.read();
}

void blur_Mat2AXIM::thread_grp_blur_Mat2Array_fu_34_m_axi_fb_BID() {
    grp_blur_Mat2Array_fu_34_m_axi_fb_BID = m_axi_fb_BID.read();
}

void blur_Mat2AXIM::thread_grp_blur_Mat2Array_fu_34_m_axi_fb_BRESP() {
    grp_blur_Mat2Array_fu_34_m_axi_fb_BRESP = m_axi_fb_BRESP.read();
}

void blur_Mat2AXIM::thread_grp_blur_Mat2Array_fu_34_m_axi_fb_BUSER() {
    grp_blur_Mat2Array_fu_34_m_axi_fb_BUSER = m_axi_fb_BUSER.read();
}

void blur_Mat2AXIM::thread_grp_blur_Mat2Array_fu_34_m_axi_fb_BVALID() {
    grp_blur_Mat2Array_fu_34_m_axi_fb_BVALID = m_axi_fb_BVALID.read();
}

void blur_Mat2AXIM::thread_grp_blur_Mat2Array_fu_34_m_axi_fb_RDATA() {
    grp_blur_Mat2Array_fu_34_m_axi_fb_RDATA = ap_const_lv8_0;
}

void blur_Mat2AXIM::thread_grp_blur_Mat2Array_fu_34_m_axi_fb_RID() {
    grp_blur_Mat2Array_fu_34_m_axi_fb_RID = ap_const_lv1_0;
}

void blur_Mat2AXIM::thread_grp_blur_Mat2Array_fu_34_m_axi_fb_RLAST() {
    grp_blur_Mat2Array_fu_34_m_axi_fb_RLAST = ap_const_logic_0;
}

void blur_Mat2AXIM::thread_grp_blur_Mat2Array_fu_34_m_axi_fb_RRESP() {
    grp_blur_Mat2Array_fu_34_m_axi_fb_RRESP = ap_const_lv2_0;
}

void blur_Mat2AXIM::thread_grp_blur_Mat2Array_fu_34_m_axi_fb_RUSER() {
    grp_blur_Mat2Array_fu_34_m_axi_fb_RUSER = ap_const_lv1_0;
}

void blur_Mat2AXIM::thread_grp_blur_Mat2Array_fu_34_m_axi_fb_RVALID() {
    grp_blur_Mat2Array_fu_34_m_axi_fb_RVALID = ap_const_logic_0;
}

void blur_Mat2AXIM::thread_grp_blur_Mat2Array_fu_34_m_axi_fb_WREADY() {
    grp_blur_Mat2Array_fu_34_m_axi_fb_WREADY = m_axi_fb_WREADY.read();
}

void blur_Mat2AXIM::thread_image_out_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
         !ap_sig_bdd_98.read())) {
        image_out_read = ap_const_logic_1;
    } else {
        image_out_read = ap_const_logic_0;
    }
}

void blur_Mat2AXIM::thread_img_data_stream_V_read() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        img_data_stream_V_read = grp_blur_Mat2Array_fu_34_img_data_stream_V_read.read();
    } else {
        img_data_stream_V_read = ap_const_logic_0;
    }
}

void blur_Mat2AXIM::thread_m_axi_fb_ARADDR() {
    m_axi_fb_ARADDR = ap_const_lv32_0;
}

void blur_Mat2AXIM::thread_m_axi_fb_ARBURST() {
    m_axi_fb_ARBURST = ap_const_lv2_0;
}

void blur_Mat2AXIM::thread_m_axi_fb_ARCACHE() {
    m_axi_fb_ARCACHE = ap_const_lv4_0;
}

void blur_Mat2AXIM::thread_m_axi_fb_ARID() {
    m_axi_fb_ARID = ap_const_lv1_0;
}

void blur_Mat2AXIM::thread_m_axi_fb_ARLEN() {
    m_axi_fb_ARLEN = ap_const_lv32_0;
}

void blur_Mat2AXIM::thread_m_axi_fb_ARLOCK() {
    m_axi_fb_ARLOCK = ap_const_lv2_0;
}

void blur_Mat2AXIM::thread_m_axi_fb_ARPROT() {
    m_axi_fb_ARPROT = ap_const_lv3_0;
}

void blur_Mat2AXIM::thread_m_axi_fb_ARQOS() {
    m_axi_fb_ARQOS = ap_const_lv4_0;
}

void blur_Mat2AXIM::thread_m_axi_fb_ARREGION() {
    m_axi_fb_ARREGION = ap_const_lv4_0;
}

void blur_Mat2AXIM::thread_m_axi_fb_ARSIZE() {
    m_axi_fb_ARSIZE = ap_const_lv3_0;
}

void blur_Mat2AXIM::thread_m_axi_fb_ARUSER() {
    m_axi_fb_ARUSER = ap_const_lv1_0;
}

void blur_Mat2AXIM::thread_m_axi_fb_ARVALID() {
    m_axi_fb_ARVALID = ap_const_logic_0;
}

void blur_Mat2AXIM::thread_m_axi_fb_AWADDR() {
    m_axi_fb_AWADDR = grp_blur_Mat2Array_fu_34_m_axi_fb_AWADDR.read();
}

void blur_Mat2AXIM::thread_m_axi_fb_AWBURST() {
    m_axi_fb_AWBURST = grp_blur_Mat2Array_fu_34_m_axi_fb_AWBURST.read();
}

void blur_Mat2AXIM::thread_m_axi_fb_AWCACHE() {
    m_axi_fb_AWCACHE = grp_blur_Mat2Array_fu_34_m_axi_fb_AWCACHE.read();
}

void blur_Mat2AXIM::thread_m_axi_fb_AWID() {
    m_axi_fb_AWID = grp_blur_Mat2Array_fu_34_m_axi_fb_AWID.read();
}

void blur_Mat2AXIM::thread_m_axi_fb_AWLEN() {
    m_axi_fb_AWLEN = grp_blur_Mat2Array_fu_34_m_axi_fb_AWLEN.read();
}

void blur_Mat2AXIM::thread_m_axi_fb_AWLOCK() {
    m_axi_fb_AWLOCK = grp_blur_Mat2Array_fu_34_m_axi_fb_AWLOCK.read();
}

void blur_Mat2AXIM::thread_m_axi_fb_AWPROT() {
    m_axi_fb_AWPROT = grp_blur_Mat2Array_fu_34_m_axi_fb_AWPROT.read();
}

void blur_Mat2AXIM::thread_m_axi_fb_AWQOS() {
    m_axi_fb_AWQOS = grp_blur_Mat2Array_fu_34_m_axi_fb_AWQOS.read();
}

void blur_Mat2AXIM::thread_m_axi_fb_AWREGION() {
    m_axi_fb_AWREGION = grp_blur_Mat2Array_fu_34_m_axi_fb_AWREGION.read();
}

void blur_Mat2AXIM::thread_m_axi_fb_AWSIZE() {
    m_axi_fb_AWSIZE = grp_blur_Mat2Array_fu_34_m_axi_fb_AWSIZE.read();
}

void blur_Mat2AXIM::thread_m_axi_fb_AWUSER() {
    m_axi_fb_AWUSER = grp_blur_Mat2Array_fu_34_m_axi_fb_AWUSER.read();
}

void blur_Mat2AXIM::thread_m_axi_fb_AWVALID() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()))) {
        m_axi_fb_AWVALID = grp_blur_Mat2Array_fu_34_m_axi_fb_AWVALID.read();
    } else {
        m_axi_fb_AWVALID = ap_const_logic_0;
    }
}

void blur_Mat2AXIM::thread_m_axi_fb_BREADY() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()))) {
        m_axi_fb_BREADY = grp_blur_Mat2Array_fu_34_m_axi_fb_BREADY.read();
    } else {
        m_axi_fb_BREADY = ap_const_logic_0;
    }
}

void blur_Mat2AXIM::thread_m_axi_fb_RREADY() {
    m_axi_fb_RREADY = ap_const_logic_0;
}

void blur_Mat2AXIM::thread_m_axi_fb_WDATA() {
    m_axi_fb_WDATA = grp_blur_Mat2Array_fu_34_m_axi_fb_WDATA.read();
}

void blur_Mat2AXIM::thread_m_axi_fb_WID() {
    m_axi_fb_WID = grp_blur_Mat2Array_fu_34_m_axi_fb_WID.read();
}

void blur_Mat2AXIM::thread_m_axi_fb_WLAST() {
    m_axi_fb_WLAST = grp_blur_Mat2Array_fu_34_m_axi_fb_WLAST.read();
}

void blur_Mat2AXIM::thread_m_axi_fb_WSTRB() {
    m_axi_fb_WSTRB = grp_blur_Mat2Array_fu_34_m_axi_fb_WSTRB.read();
}

void blur_Mat2AXIM::thread_m_axi_fb_WUSER() {
    m_axi_fb_WUSER = grp_blur_Mat2Array_fu_34_m_axi_fb_WUSER.read();
}

void blur_Mat2AXIM::thread_m_axi_fb_WVALID() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()))) {
        m_axi_fb_WVALID = grp_blur_Mat2Array_fu_34_m_axi_fb_WVALID.read();
    } else {
        m_axi_fb_WVALID = ap_const_logic_0;
    }
}

void blur_Mat2AXIM::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!ap_sig_bdd_98.read()) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            if (!esl_seteq<1,1,1>(ap_const_logic_0, grp_blur_Mat2Array_fu_34_ap_done.read())) {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            } else {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            }
            break;
        default : 
            ap_NS_fsm = "XX";
            break;
    }
}

}

