// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#ifndef _blur_Mat2AXIM_HH_
#define _blur_Mat2AXIM_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "blur_Mat2Array.h"

namespace ap_rtl {

struct blur_Mat2AXIM : public sc_module {
    // Port declarations 58
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_in< sc_logic > ap_continue;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<8> > img_data_stream_V_dout;
    sc_in< sc_logic > img_data_stream_V_empty_n;
    sc_out< sc_logic > img_data_stream_V_read;
    sc_out< sc_logic > m_axi_fb_AWVALID;
    sc_in< sc_logic > m_axi_fb_AWREADY;
    sc_out< sc_lv<32> > m_axi_fb_AWADDR;
    sc_out< sc_lv<1> > m_axi_fb_AWID;
    sc_out< sc_lv<32> > m_axi_fb_AWLEN;
    sc_out< sc_lv<3> > m_axi_fb_AWSIZE;
    sc_out< sc_lv<2> > m_axi_fb_AWBURST;
    sc_out< sc_lv<2> > m_axi_fb_AWLOCK;
    sc_out< sc_lv<4> > m_axi_fb_AWCACHE;
    sc_out< sc_lv<3> > m_axi_fb_AWPROT;
    sc_out< sc_lv<4> > m_axi_fb_AWQOS;
    sc_out< sc_lv<4> > m_axi_fb_AWREGION;
    sc_out< sc_lv<1> > m_axi_fb_AWUSER;
    sc_out< sc_logic > m_axi_fb_WVALID;
    sc_in< sc_logic > m_axi_fb_WREADY;
    sc_out< sc_lv<8> > m_axi_fb_WDATA;
    sc_out< sc_lv<1> > m_axi_fb_WSTRB;
    sc_out< sc_logic > m_axi_fb_WLAST;
    sc_out< sc_lv<1> > m_axi_fb_WID;
    sc_out< sc_lv<1> > m_axi_fb_WUSER;
    sc_out< sc_logic > m_axi_fb_ARVALID;
    sc_in< sc_logic > m_axi_fb_ARREADY;
    sc_out< sc_lv<32> > m_axi_fb_ARADDR;
    sc_out< sc_lv<1> > m_axi_fb_ARID;
    sc_out< sc_lv<32> > m_axi_fb_ARLEN;
    sc_out< sc_lv<3> > m_axi_fb_ARSIZE;
    sc_out< sc_lv<2> > m_axi_fb_ARBURST;
    sc_out< sc_lv<2> > m_axi_fb_ARLOCK;
    sc_out< sc_lv<4> > m_axi_fb_ARCACHE;
    sc_out< sc_lv<3> > m_axi_fb_ARPROT;
    sc_out< sc_lv<4> > m_axi_fb_ARQOS;
    sc_out< sc_lv<4> > m_axi_fb_ARREGION;
    sc_out< sc_lv<1> > m_axi_fb_ARUSER;
    sc_in< sc_logic > m_axi_fb_RVALID;
    sc_out< sc_logic > m_axi_fb_RREADY;
    sc_in< sc_lv<8> > m_axi_fb_RDATA;
    sc_in< sc_logic > m_axi_fb_RLAST;
    sc_in< sc_lv<1> > m_axi_fb_RID;
    sc_in< sc_lv<1> > m_axi_fb_RUSER;
    sc_in< sc_lv<2> > m_axi_fb_RRESP;
    sc_in< sc_logic > m_axi_fb_BVALID;
    sc_out< sc_logic > m_axi_fb_BREADY;
    sc_in< sc_lv<2> > m_axi_fb_BRESP;
    sc_in< sc_lv<1> > m_axi_fb_BID;
    sc_in< sc_lv<1> > m_axi_fb_BUSER;
    sc_in< sc_lv<32> > image_out_dout;
    sc_in< sc_logic > image_out_empty_n;
    sc_out< sc_logic > image_out_read;


    // Module declarations
    blur_Mat2AXIM(sc_module_name name);
    SC_HAS_PROCESS(blur_Mat2AXIM);

    ~blur_Mat2AXIM();

    sc_trace_file* mVcdFile;

    blur_Mat2Array* grp_blur_Mat2Array_fu_34;
    sc_signal< sc_logic > ap_done_reg;
    sc_signal< sc_lv<2> > ap_CS_fsm;
    sc_signal< sc_logic > ap_sig_cseq_ST_st1_fsm_0;
    sc_signal< bool > ap_sig_bdd_21;
    sc_signal< sc_lv<32> > image_out_read_reg_44;
    sc_signal< bool > ap_sig_bdd_98;
    sc_signal< sc_logic > grp_blur_Mat2Array_fu_34_ap_start;
    sc_signal< sc_logic > grp_blur_Mat2Array_fu_34_ap_done;
    sc_signal< sc_logic > grp_blur_Mat2Array_fu_34_ap_idle;
    sc_signal< sc_logic > grp_blur_Mat2Array_fu_34_ap_ready;
    sc_signal< sc_lv<8> > grp_blur_Mat2Array_fu_34_img_data_stream_V_dout;
    sc_signal< sc_logic > grp_blur_Mat2Array_fu_34_img_data_stream_V_empty_n;
    sc_signal< sc_logic > grp_blur_Mat2Array_fu_34_img_data_stream_V_read;
    sc_signal< sc_logic > grp_blur_Mat2Array_fu_34_m_axi_fb_AWVALID;
    sc_signal< sc_logic > grp_blur_Mat2Array_fu_34_m_axi_fb_AWREADY;
    sc_signal< sc_lv<32> > grp_blur_Mat2Array_fu_34_m_axi_fb_AWADDR;
    sc_signal< sc_lv<1> > grp_blur_Mat2Array_fu_34_m_axi_fb_AWID;
    sc_signal< sc_lv<32> > grp_blur_Mat2Array_fu_34_m_axi_fb_AWLEN;
    sc_signal< sc_lv<3> > grp_blur_Mat2Array_fu_34_m_axi_fb_AWSIZE;
    sc_signal< sc_lv<2> > grp_blur_Mat2Array_fu_34_m_axi_fb_AWBURST;
    sc_signal< sc_lv<2> > grp_blur_Mat2Array_fu_34_m_axi_fb_AWLOCK;
    sc_signal< sc_lv<4> > grp_blur_Mat2Array_fu_34_m_axi_fb_AWCACHE;
    sc_signal< sc_lv<3> > grp_blur_Mat2Array_fu_34_m_axi_fb_AWPROT;
    sc_signal< sc_lv<4> > grp_blur_Mat2Array_fu_34_m_axi_fb_AWQOS;
    sc_signal< sc_lv<4> > grp_blur_Mat2Array_fu_34_m_axi_fb_AWREGION;
    sc_signal< sc_lv<1> > grp_blur_Mat2Array_fu_34_m_axi_fb_AWUSER;
    sc_signal< sc_logic > grp_blur_Mat2Array_fu_34_m_axi_fb_WVALID;
    sc_signal< sc_logic > grp_blur_Mat2Array_fu_34_m_axi_fb_WREADY;
    sc_signal< sc_lv<8> > grp_blur_Mat2Array_fu_34_m_axi_fb_WDATA;
    sc_signal< sc_lv<1> > grp_blur_Mat2Array_fu_34_m_axi_fb_WSTRB;
    sc_signal< sc_logic > grp_blur_Mat2Array_fu_34_m_axi_fb_WLAST;
    sc_signal< sc_lv<1> > grp_blur_Mat2Array_fu_34_m_axi_fb_WID;
    sc_signal< sc_lv<1> > grp_blur_Mat2Array_fu_34_m_axi_fb_WUSER;
    sc_signal< sc_logic > grp_blur_Mat2Array_fu_34_m_axi_fb_ARVALID;
    sc_signal< sc_logic > grp_blur_Mat2Array_fu_34_m_axi_fb_ARREADY;
    sc_signal< sc_lv<32> > grp_blur_Mat2Array_fu_34_m_axi_fb_ARADDR;
    sc_signal< sc_lv<1> > grp_blur_Mat2Array_fu_34_m_axi_fb_ARID;
    sc_signal< sc_lv<32> > grp_blur_Mat2Array_fu_34_m_axi_fb_ARLEN;
    sc_signal< sc_lv<3> > grp_blur_Mat2Array_fu_34_m_axi_fb_ARSIZE;
    sc_signal< sc_lv<2> > grp_blur_Mat2Array_fu_34_m_axi_fb_ARBURST;
    sc_signal< sc_lv<2> > grp_blur_Mat2Array_fu_34_m_axi_fb_ARLOCK;
    sc_signal< sc_lv<4> > grp_blur_Mat2Array_fu_34_m_axi_fb_ARCACHE;
    sc_signal< sc_lv<3> > grp_blur_Mat2Array_fu_34_m_axi_fb_ARPROT;
    sc_signal< sc_lv<4> > grp_blur_Mat2Array_fu_34_m_axi_fb_ARQOS;
    sc_signal< sc_lv<4> > grp_blur_Mat2Array_fu_34_m_axi_fb_ARREGION;
    sc_signal< sc_lv<1> > grp_blur_Mat2Array_fu_34_m_axi_fb_ARUSER;
    sc_signal< sc_logic > grp_blur_Mat2Array_fu_34_m_axi_fb_RVALID;
    sc_signal< sc_logic > grp_blur_Mat2Array_fu_34_m_axi_fb_RREADY;
    sc_signal< sc_lv<8> > grp_blur_Mat2Array_fu_34_m_axi_fb_RDATA;
    sc_signal< sc_logic > grp_blur_Mat2Array_fu_34_m_axi_fb_RLAST;
    sc_signal< sc_lv<1> > grp_blur_Mat2Array_fu_34_m_axi_fb_RID;
    sc_signal< sc_lv<1> > grp_blur_Mat2Array_fu_34_m_axi_fb_RUSER;
    sc_signal< sc_lv<2> > grp_blur_Mat2Array_fu_34_m_axi_fb_RRESP;
    sc_signal< sc_logic > grp_blur_Mat2Array_fu_34_m_axi_fb_BVALID;
    sc_signal< sc_logic > grp_blur_Mat2Array_fu_34_m_axi_fb_BREADY;
    sc_signal< sc_lv<2> > grp_blur_Mat2Array_fu_34_m_axi_fb_BRESP;
    sc_signal< sc_lv<1> > grp_blur_Mat2Array_fu_34_m_axi_fb_BID;
    sc_signal< sc_lv<1> > grp_blur_Mat2Array_fu_34_m_axi_fb_BUSER;
    sc_signal< sc_lv<32> > grp_blur_Mat2Array_fu_34_image_out1;
    sc_signal< sc_logic > grp_blur_Mat2Array_fu_34_ap_start_ap_start_reg;
    sc_signal< sc_logic > ap_sig_cseq_ST_st2_fsm_1;
    sc_signal< bool > ap_sig_bdd_163;
    sc_signal< sc_lv<2> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<2> ap_ST_st1_fsm_0;
    static const sc_lv<2> ap_ST_st2_fsm_1;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<3> ap_const_lv3_0;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<8> ap_const_lv8_0;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_sig_bdd_163();
    void thread_ap_sig_bdd_21();
    void thread_ap_sig_bdd_98();
    void thread_ap_sig_cseq_ST_st1_fsm_0();
    void thread_ap_sig_cseq_ST_st2_fsm_1();
    void thread_grp_blur_Mat2Array_fu_34_ap_start();
    void thread_grp_blur_Mat2Array_fu_34_image_out1();
    void thread_grp_blur_Mat2Array_fu_34_img_data_stream_V_dout();
    void thread_grp_blur_Mat2Array_fu_34_img_data_stream_V_empty_n();
    void thread_grp_blur_Mat2Array_fu_34_m_axi_fb_ARREADY();
    void thread_grp_blur_Mat2Array_fu_34_m_axi_fb_AWREADY();
    void thread_grp_blur_Mat2Array_fu_34_m_axi_fb_BID();
    void thread_grp_blur_Mat2Array_fu_34_m_axi_fb_BRESP();
    void thread_grp_blur_Mat2Array_fu_34_m_axi_fb_BUSER();
    void thread_grp_blur_Mat2Array_fu_34_m_axi_fb_BVALID();
    void thread_grp_blur_Mat2Array_fu_34_m_axi_fb_RDATA();
    void thread_grp_blur_Mat2Array_fu_34_m_axi_fb_RID();
    void thread_grp_blur_Mat2Array_fu_34_m_axi_fb_RLAST();
    void thread_grp_blur_Mat2Array_fu_34_m_axi_fb_RRESP();
    void thread_grp_blur_Mat2Array_fu_34_m_axi_fb_RUSER();
    void thread_grp_blur_Mat2Array_fu_34_m_axi_fb_RVALID();
    void thread_grp_blur_Mat2Array_fu_34_m_axi_fb_WREADY();
    void thread_image_out_read();
    void thread_img_data_stream_V_read();
    void thread_m_axi_fb_ARADDR();
    void thread_m_axi_fb_ARBURST();
    void thread_m_axi_fb_ARCACHE();
    void thread_m_axi_fb_ARID();
    void thread_m_axi_fb_ARLEN();
    void thread_m_axi_fb_ARLOCK();
    void thread_m_axi_fb_ARPROT();
    void thread_m_axi_fb_ARQOS();
    void thread_m_axi_fb_ARREGION();
    void thread_m_axi_fb_ARSIZE();
    void thread_m_axi_fb_ARUSER();
    void thread_m_axi_fb_ARVALID();
    void thread_m_axi_fb_AWADDR();
    void thread_m_axi_fb_AWBURST();
    void thread_m_axi_fb_AWCACHE();
    void thread_m_axi_fb_AWID();
    void thread_m_axi_fb_AWLEN();
    void thread_m_axi_fb_AWLOCK();
    void thread_m_axi_fb_AWPROT();
    void thread_m_axi_fb_AWQOS();
    void thread_m_axi_fb_AWREGION();
    void thread_m_axi_fb_AWSIZE();
    void thread_m_axi_fb_AWUSER();
    void thread_m_axi_fb_AWVALID();
    void thread_m_axi_fb_BREADY();
    void thread_m_axi_fb_RREADY();
    void thread_m_axi_fb_WDATA();
    void thread_m_axi_fb_WID();
    void thread_m_axi_fb_WLAST();
    void thread_m_axi_fb_WSTRB();
    void thread_m_axi_fb_WUSER();
    void thread_m_axi_fb_WVALID();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
