// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#ifndef _blur_Block_proc9_HH_
#define _blur_Block_proc9_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct blur_Block_proc9 : public sc_module {
    // Port declarations 21
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_in< sc_logic > ap_continue;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<12> > src_rows_V_out_din;
    sc_in< sc_logic > src_rows_V_out_full_n;
    sc_out< sc_logic > src_rows_V_out_write;
    sc_out< sc_lv<12> > src_cols_V_out_din;
    sc_in< sc_logic > src_cols_V_out_full_n;
    sc_out< sc_logic > src_cols_V_out_write;
    sc_in< sc_lv<32> > image_in;
    sc_in< sc_lv<32> > image_out;
    sc_out< sc_lv<32> > image_in_out_din;
    sc_in< sc_logic > image_in_out_full_n;
    sc_out< sc_logic > image_in_out_write;
    sc_out< sc_lv<32> > image_out_out_din;
    sc_in< sc_logic > image_out_out_full_n;
    sc_out< sc_logic > image_out_out_write;


    // Module declarations
    blur_Block_proc9(sc_module_name name);
    SC_HAS_PROCESS(blur_Block_proc9);

    ~blur_Block_proc9();

    sc_trace_file* mVcdFile;

    sc_signal< sc_logic > ap_done_reg;
    sc_signal< sc_lv<1> > ap_CS_fsm;
    sc_signal< sc_logic > ap_sig_cseq_ST_st1_fsm_0;
    sc_signal< bool > ap_sig_bdd_20;
    sc_signal< bool > ap_sig_bdd_57;
    sc_signal< sc_lv<1> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<1> ap_ST_st1_fsm_0;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<12> ap_const_lv12_438;
    static const sc_lv<12> ap_const_lv12_780;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_sig_bdd_20();
    void thread_ap_sig_bdd_57();
    void thread_ap_sig_cseq_ST_st1_fsm_0();
    void thread_image_in_out_din();
    void thread_image_in_out_write();
    void thread_image_out_out_din();
    void thread_image_out_out_write();
    void thread_src_cols_V_out_din();
    void thread_src_cols_V_out_write();
    void thread_src_rows_V_out_din();
    void thread_src_rows_V_out_write();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
