// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#include "blur_AXIM2Mat.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic blur_AXIM2Mat::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic blur_AXIM2Mat::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<2> blur_AXIM2Mat::ap_ST_st1_fsm_0 = "1";
const sc_lv<2> blur_AXIM2Mat::ap_ST_st2_fsm_1 = "10";
const sc_lv<32> blur_AXIM2Mat::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> blur_AXIM2Mat::ap_const_lv1_1 = "1";
const sc_lv<1> blur_AXIM2Mat::ap_const_lv1_0 = "0";
const sc_lv<3> blur_AXIM2Mat::ap_const_lv3_0 = "000";
const sc_lv<2> blur_AXIM2Mat::ap_const_lv2_0 = "00";
const sc_lv<4> blur_AXIM2Mat::ap_const_lv4_0 = "0000";
const sc_lv<8> blur_AXIM2Mat::ap_const_lv8_0 = "00000000";
const sc_lv<32> blur_AXIM2Mat::ap_const_lv32_1 = "1";

blur_AXIM2Mat::blur_AXIM2Mat(sc_module_name name) : sc_module(name), mVcdFile(0) {
    grp_blur_Array2Mat_fu_74 = new blur_Array2Mat("grp_blur_Array2Mat_fu_74");
    grp_blur_Array2Mat_fu_74->ap_clk(ap_clk);
    grp_blur_Array2Mat_fu_74->ap_rst(ap_rst);
    grp_blur_Array2Mat_fu_74->ap_start(grp_blur_Array2Mat_fu_74_ap_start);
    grp_blur_Array2Mat_fu_74->ap_done(grp_blur_Array2Mat_fu_74_ap_done);
    grp_blur_Array2Mat_fu_74->ap_idle(grp_blur_Array2Mat_fu_74_ap_idle);
    grp_blur_Array2Mat_fu_74->ap_ready(grp_blur_Array2Mat_fu_74_ap_ready);
    grp_blur_Array2Mat_fu_74->m_axi_fb_AWVALID(grp_blur_Array2Mat_fu_74_m_axi_fb_AWVALID);
    grp_blur_Array2Mat_fu_74->m_axi_fb_AWREADY(grp_blur_Array2Mat_fu_74_m_axi_fb_AWREADY);
    grp_blur_Array2Mat_fu_74->m_axi_fb_AWADDR(grp_blur_Array2Mat_fu_74_m_axi_fb_AWADDR);
    grp_blur_Array2Mat_fu_74->m_axi_fb_AWID(grp_blur_Array2Mat_fu_74_m_axi_fb_AWID);
    grp_blur_Array2Mat_fu_74->m_axi_fb_AWLEN(grp_blur_Array2Mat_fu_74_m_axi_fb_AWLEN);
    grp_blur_Array2Mat_fu_74->m_axi_fb_AWSIZE(grp_blur_Array2Mat_fu_74_m_axi_fb_AWSIZE);
    grp_blur_Array2Mat_fu_74->m_axi_fb_AWBURST(grp_blur_Array2Mat_fu_74_m_axi_fb_AWBURST);
    grp_blur_Array2Mat_fu_74->m_axi_fb_AWLOCK(grp_blur_Array2Mat_fu_74_m_axi_fb_AWLOCK);
    grp_blur_Array2Mat_fu_74->m_axi_fb_AWCACHE(grp_blur_Array2Mat_fu_74_m_axi_fb_AWCACHE);
    grp_blur_Array2Mat_fu_74->m_axi_fb_AWPROT(grp_blur_Array2Mat_fu_74_m_axi_fb_AWPROT);
    grp_blur_Array2Mat_fu_74->m_axi_fb_AWQOS(grp_blur_Array2Mat_fu_74_m_axi_fb_AWQOS);
    grp_blur_Array2Mat_fu_74->m_axi_fb_AWREGION(grp_blur_Array2Mat_fu_74_m_axi_fb_AWREGION);
    grp_blur_Array2Mat_fu_74->m_axi_fb_AWUSER(grp_blur_Array2Mat_fu_74_m_axi_fb_AWUSER);
    grp_blur_Array2Mat_fu_74->m_axi_fb_WVALID(grp_blur_Array2Mat_fu_74_m_axi_fb_WVALID);
    grp_blur_Array2Mat_fu_74->m_axi_fb_WREADY(grp_blur_Array2Mat_fu_74_m_axi_fb_WREADY);
    grp_blur_Array2Mat_fu_74->m_axi_fb_WDATA(grp_blur_Array2Mat_fu_74_m_axi_fb_WDATA);
    grp_blur_Array2Mat_fu_74->m_axi_fb_WSTRB(grp_blur_Array2Mat_fu_74_m_axi_fb_WSTRB);
    grp_blur_Array2Mat_fu_74->m_axi_fb_WLAST(grp_blur_Array2Mat_fu_74_m_axi_fb_WLAST);
    grp_blur_Array2Mat_fu_74->m_axi_fb_WID(grp_blur_Array2Mat_fu_74_m_axi_fb_WID);
    grp_blur_Array2Mat_fu_74->m_axi_fb_WUSER(grp_blur_Array2Mat_fu_74_m_axi_fb_WUSER);
    grp_blur_Array2Mat_fu_74->m_axi_fb_ARVALID(grp_blur_Array2Mat_fu_74_m_axi_fb_ARVALID);
    grp_blur_Array2Mat_fu_74->m_axi_fb_ARREADY(grp_blur_Array2Mat_fu_74_m_axi_fb_ARREADY);
    grp_blur_Array2Mat_fu_74->m_axi_fb_ARADDR(grp_blur_Array2Mat_fu_74_m_axi_fb_ARADDR);
    grp_blur_Array2Mat_fu_74->m_axi_fb_ARID(grp_blur_Array2Mat_fu_74_m_axi_fb_ARID);
    grp_blur_Array2Mat_fu_74->m_axi_fb_ARLEN(grp_blur_Array2Mat_fu_74_m_axi_fb_ARLEN);
    grp_blur_Array2Mat_fu_74->m_axi_fb_ARSIZE(grp_blur_Array2Mat_fu_74_m_axi_fb_ARSIZE);
    grp_blur_Array2Mat_fu_74->m_axi_fb_ARBURST(grp_blur_Array2Mat_fu_74_m_axi_fb_ARBURST);
    grp_blur_Array2Mat_fu_74->m_axi_fb_ARLOCK(grp_blur_Array2Mat_fu_74_m_axi_fb_ARLOCK);
    grp_blur_Array2Mat_fu_74->m_axi_fb_ARCACHE(grp_blur_Array2Mat_fu_74_m_axi_fb_ARCACHE);
    grp_blur_Array2Mat_fu_74->m_axi_fb_ARPROT(grp_blur_Array2Mat_fu_74_m_axi_fb_ARPROT);
    grp_blur_Array2Mat_fu_74->m_axi_fb_ARQOS(grp_blur_Array2Mat_fu_74_m_axi_fb_ARQOS);
    grp_blur_Array2Mat_fu_74->m_axi_fb_ARREGION(grp_blur_Array2Mat_fu_74_m_axi_fb_ARREGION);
    grp_blur_Array2Mat_fu_74->m_axi_fb_ARUSER(grp_blur_Array2Mat_fu_74_m_axi_fb_ARUSER);
    grp_blur_Array2Mat_fu_74->m_axi_fb_RVALID(grp_blur_Array2Mat_fu_74_m_axi_fb_RVALID);
    grp_blur_Array2Mat_fu_74->m_axi_fb_RREADY(grp_blur_Array2Mat_fu_74_m_axi_fb_RREADY);
    grp_blur_Array2Mat_fu_74->m_axi_fb_RDATA(grp_blur_Array2Mat_fu_74_m_axi_fb_RDATA);
    grp_blur_Array2Mat_fu_74->m_axi_fb_RLAST(grp_blur_Array2Mat_fu_74_m_axi_fb_RLAST);
    grp_blur_Array2Mat_fu_74->m_axi_fb_RID(grp_blur_Array2Mat_fu_74_m_axi_fb_RID);
    grp_blur_Array2Mat_fu_74->m_axi_fb_RUSER(grp_blur_Array2Mat_fu_74_m_axi_fb_RUSER);
    grp_blur_Array2Mat_fu_74->m_axi_fb_RRESP(grp_blur_Array2Mat_fu_74_m_axi_fb_RRESP);
    grp_blur_Array2Mat_fu_74->m_axi_fb_BVALID(grp_blur_Array2Mat_fu_74_m_axi_fb_BVALID);
    grp_blur_Array2Mat_fu_74->m_axi_fb_BREADY(grp_blur_Array2Mat_fu_74_m_axi_fb_BREADY);
    grp_blur_Array2Mat_fu_74->m_axi_fb_BRESP(grp_blur_Array2Mat_fu_74_m_axi_fb_BRESP);
    grp_blur_Array2Mat_fu_74->m_axi_fb_BID(grp_blur_Array2Mat_fu_74_m_axi_fb_BID);
    grp_blur_Array2Mat_fu_74->m_axi_fb_BUSER(grp_blur_Array2Mat_fu_74_m_axi_fb_BUSER);
    grp_blur_Array2Mat_fu_74->image_in1(grp_blur_Array2Mat_fu_74_image_in1);
    grp_blur_Array2Mat_fu_74->img_rows_V_read(grp_blur_Array2Mat_fu_74_img_rows_V_read);
    grp_blur_Array2Mat_fu_74->img_cols_V_read(grp_blur_Array2Mat_fu_74_img_cols_V_read);
    grp_blur_Array2Mat_fu_74->img_data_stream_V_din(grp_blur_Array2Mat_fu_74_img_data_stream_V_din);
    grp_blur_Array2Mat_fu_74->img_data_stream_V_full_n(grp_blur_Array2Mat_fu_74_img_data_stream_V_full_n);
    grp_blur_Array2Mat_fu_74->img_data_stream_V_write(grp_blur_Array2Mat_fu_74_img_data_stream_V_write);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( grp_blur_Array2Mat_fu_74_ap_done );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( grp_blur_Array2Mat_fu_74_ap_done );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_ap_sig_bdd_123);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( image_in_empty_n );
    sensitive << ( img_rows_V_empty_n );
    sensitive << ( img_cols_V_empty_n );
    sensitive << ( img_rows_V_out_full_n );
    sensitive << ( img_cols_V_out_full_n );

    SC_METHOD(thread_ap_sig_bdd_194);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_21);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_bdd_21 );

    SC_METHOD(thread_ap_sig_cseq_ST_st2_fsm_1);
    sensitive << ( ap_sig_bdd_194 );

    SC_METHOD(thread_grp_blur_Array2Mat_fu_74_ap_start);
    sensitive << ( grp_blur_Array2Mat_fu_74_ap_start_ap_start_reg );

    SC_METHOD(thread_grp_blur_Array2Mat_fu_74_image_in1);
    sensitive << ( image_in_read_reg_88 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_blur_Array2Mat_fu_74_img_cols_V_read);
    sensitive << ( img_cols_V_read_reg_98 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_blur_Array2Mat_fu_74_img_data_stream_V_full_n);
    sensitive << ( img_data_stream_V_full_n );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_blur_Array2Mat_fu_74_img_rows_V_read);
    sensitive << ( img_rows_V_read_reg_93 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_blur_Array2Mat_fu_74_m_axi_fb_ARREADY);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( m_axi_fb_ARREADY );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_blur_Array2Mat_fu_74_m_axi_fb_AWREADY);

    SC_METHOD(thread_grp_blur_Array2Mat_fu_74_m_axi_fb_BID);

    SC_METHOD(thread_grp_blur_Array2Mat_fu_74_m_axi_fb_BRESP);

    SC_METHOD(thread_grp_blur_Array2Mat_fu_74_m_axi_fb_BUSER);

    SC_METHOD(thread_grp_blur_Array2Mat_fu_74_m_axi_fb_BVALID);

    SC_METHOD(thread_grp_blur_Array2Mat_fu_74_m_axi_fb_RDATA);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( m_axi_fb_RDATA );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_blur_Array2Mat_fu_74_m_axi_fb_RID);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( m_axi_fb_RID );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_blur_Array2Mat_fu_74_m_axi_fb_RLAST);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( m_axi_fb_RLAST );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_blur_Array2Mat_fu_74_m_axi_fb_RRESP);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( m_axi_fb_RRESP );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_blur_Array2Mat_fu_74_m_axi_fb_RUSER);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( m_axi_fb_RUSER );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_blur_Array2Mat_fu_74_m_axi_fb_RVALID);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( m_axi_fb_RVALID );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_blur_Array2Mat_fu_74_m_axi_fb_WREADY);

    SC_METHOD(thread_image_in_read);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_sig_bdd_123 );

    SC_METHOD(thread_img_cols_V_out_din);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( img_cols_V_dout );
    sensitive << ( ap_sig_bdd_123 );

    SC_METHOD(thread_img_cols_V_out_write);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_sig_bdd_123 );

    SC_METHOD(thread_img_cols_V_read);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_sig_bdd_123 );

    SC_METHOD(thread_img_data_stream_V_din);
    sensitive << ( grp_blur_Array2Mat_fu_74_img_data_stream_V_din );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_img_data_stream_V_write);
    sensitive << ( grp_blur_Array2Mat_fu_74_img_data_stream_V_write );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_img_rows_V_out_din);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( img_rows_V_dout );
    sensitive << ( ap_sig_bdd_123 );

    SC_METHOD(thread_img_rows_V_out_write);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_sig_bdd_123 );

    SC_METHOD(thread_img_rows_V_read);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_sig_bdd_123 );

    SC_METHOD(thread_m_axi_fb_ARADDR);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( grp_blur_Array2Mat_fu_74_m_axi_fb_ARADDR );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_m_axi_fb_ARBURST);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( grp_blur_Array2Mat_fu_74_m_axi_fb_ARBURST );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_m_axi_fb_ARCACHE);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( grp_blur_Array2Mat_fu_74_m_axi_fb_ARCACHE );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_m_axi_fb_ARID);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( grp_blur_Array2Mat_fu_74_m_axi_fb_ARID );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_m_axi_fb_ARLEN);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( grp_blur_Array2Mat_fu_74_m_axi_fb_ARLEN );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_m_axi_fb_ARLOCK);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( grp_blur_Array2Mat_fu_74_m_axi_fb_ARLOCK );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_m_axi_fb_ARPROT);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( grp_blur_Array2Mat_fu_74_m_axi_fb_ARPROT );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_m_axi_fb_ARQOS);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( grp_blur_Array2Mat_fu_74_m_axi_fb_ARQOS );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_m_axi_fb_ARREGION);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( grp_blur_Array2Mat_fu_74_m_axi_fb_ARREGION );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_m_axi_fb_ARSIZE);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( grp_blur_Array2Mat_fu_74_m_axi_fb_ARSIZE );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_m_axi_fb_ARUSER);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( grp_blur_Array2Mat_fu_74_m_axi_fb_ARUSER );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_m_axi_fb_ARVALID);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( grp_blur_Array2Mat_fu_74_m_axi_fb_ARVALID );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_m_axi_fb_AWADDR);

    SC_METHOD(thread_m_axi_fb_AWBURST);

    SC_METHOD(thread_m_axi_fb_AWCACHE);

    SC_METHOD(thread_m_axi_fb_AWID);

    SC_METHOD(thread_m_axi_fb_AWLEN);

    SC_METHOD(thread_m_axi_fb_AWLOCK);

    SC_METHOD(thread_m_axi_fb_AWPROT);

    SC_METHOD(thread_m_axi_fb_AWQOS);

    SC_METHOD(thread_m_axi_fb_AWREGION);

    SC_METHOD(thread_m_axi_fb_AWSIZE);

    SC_METHOD(thread_m_axi_fb_AWUSER);

    SC_METHOD(thread_m_axi_fb_AWVALID);

    SC_METHOD(thread_m_axi_fb_BREADY);

    SC_METHOD(thread_m_axi_fb_RREADY);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( grp_blur_Array2Mat_fu_74_m_axi_fb_RREADY );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_m_axi_fb_WDATA);

    SC_METHOD(thread_m_axi_fb_WID);

    SC_METHOD(thread_m_axi_fb_WLAST);

    SC_METHOD(thread_m_axi_fb_WSTRB);

    SC_METHOD(thread_m_axi_fb_WUSER);

    SC_METHOD(thread_m_axi_fb_WVALID);

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_sig_bdd_123 );
    sensitive << ( grp_blur_Array2Mat_fu_74_ap_done );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "01";
    grp_blur_Array2Mat_fu_74_ap_start_ap_start_reg = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "blur_AXIM2Mat_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, m_axi_fb_AWVALID, "(port)m_axi_fb_AWVALID");
    sc_trace(mVcdFile, m_axi_fb_AWREADY, "(port)m_axi_fb_AWREADY");
    sc_trace(mVcdFile, m_axi_fb_AWADDR, "(port)m_axi_fb_AWADDR");
    sc_trace(mVcdFile, m_axi_fb_AWID, "(port)m_axi_fb_AWID");
    sc_trace(mVcdFile, m_axi_fb_AWLEN, "(port)m_axi_fb_AWLEN");
    sc_trace(mVcdFile, m_axi_fb_AWSIZE, "(port)m_axi_fb_AWSIZE");
    sc_trace(mVcdFile, m_axi_fb_AWBURST, "(port)m_axi_fb_AWBURST");
    sc_trace(mVcdFile, m_axi_fb_AWLOCK, "(port)m_axi_fb_AWLOCK");
    sc_trace(mVcdFile, m_axi_fb_AWCACHE, "(port)m_axi_fb_AWCACHE");
    sc_trace(mVcdFile, m_axi_fb_AWPROT, "(port)m_axi_fb_AWPROT");
    sc_trace(mVcdFile, m_axi_fb_AWQOS, "(port)m_axi_fb_AWQOS");
    sc_trace(mVcdFile, m_axi_fb_AWREGION, "(port)m_axi_fb_AWREGION");
    sc_trace(mVcdFile, m_axi_fb_AWUSER, "(port)m_axi_fb_AWUSER");
    sc_trace(mVcdFile, m_axi_fb_WVALID, "(port)m_axi_fb_WVALID");
    sc_trace(mVcdFile, m_axi_fb_WREADY, "(port)m_axi_fb_WREADY");
    sc_trace(mVcdFile, m_axi_fb_WDATA, "(port)m_axi_fb_WDATA");
    sc_trace(mVcdFile, m_axi_fb_WSTRB, "(port)m_axi_fb_WSTRB");
    sc_trace(mVcdFile, m_axi_fb_WLAST, "(port)m_axi_fb_WLAST");
    sc_trace(mVcdFile, m_axi_fb_WID, "(port)m_axi_fb_WID");
    sc_trace(mVcdFile, m_axi_fb_WUSER, "(port)m_axi_fb_WUSER");
    sc_trace(mVcdFile, m_axi_fb_ARVALID, "(port)m_axi_fb_ARVALID");
    sc_trace(mVcdFile, m_axi_fb_ARREADY, "(port)m_axi_fb_ARREADY");
    sc_trace(mVcdFile, m_axi_fb_ARADDR, "(port)m_axi_fb_ARADDR");
    sc_trace(mVcdFile, m_axi_fb_ARID, "(port)m_axi_fb_ARID");
    sc_trace(mVcdFile, m_axi_fb_ARLEN, "(port)m_axi_fb_ARLEN");
    sc_trace(mVcdFile, m_axi_fb_ARSIZE, "(port)m_axi_fb_ARSIZE");
    sc_trace(mVcdFile, m_axi_fb_ARBURST, "(port)m_axi_fb_ARBURST");
    sc_trace(mVcdFile, m_axi_fb_ARLOCK, "(port)m_axi_fb_ARLOCK");
    sc_trace(mVcdFile, m_axi_fb_ARCACHE, "(port)m_axi_fb_ARCACHE");
    sc_trace(mVcdFile, m_axi_fb_ARPROT, "(port)m_axi_fb_ARPROT");
    sc_trace(mVcdFile, m_axi_fb_ARQOS, "(port)m_axi_fb_ARQOS");
    sc_trace(mVcdFile, m_axi_fb_ARREGION, "(port)m_axi_fb_ARREGION");
    sc_trace(mVcdFile, m_axi_fb_ARUSER, "(port)m_axi_fb_ARUSER");
    sc_trace(mVcdFile, m_axi_fb_RVALID, "(port)m_axi_fb_RVALID");
    sc_trace(mVcdFile, m_axi_fb_RREADY, "(port)m_axi_fb_RREADY");
    sc_trace(mVcdFile, m_axi_fb_RDATA, "(port)m_axi_fb_RDATA");
    sc_trace(mVcdFile, m_axi_fb_RLAST, "(port)m_axi_fb_RLAST");
    sc_trace(mVcdFile, m_axi_fb_RID, "(port)m_axi_fb_RID");
    sc_trace(mVcdFile, m_axi_fb_RUSER, "(port)m_axi_fb_RUSER");
    sc_trace(mVcdFile, m_axi_fb_RRESP, "(port)m_axi_fb_RRESP");
    sc_trace(mVcdFile, m_axi_fb_BVALID, "(port)m_axi_fb_BVALID");
    sc_trace(mVcdFile, m_axi_fb_BREADY, "(port)m_axi_fb_BREADY");
    sc_trace(mVcdFile, m_axi_fb_BRESP, "(port)m_axi_fb_BRESP");
    sc_trace(mVcdFile, m_axi_fb_BID, "(port)m_axi_fb_BID");
    sc_trace(mVcdFile, m_axi_fb_BUSER, "(port)m_axi_fb_BUSER");
    sc_trace(mVcdFile, image_in_dout, "(port)image_in_dout");
    sc_trace(mVcdFile, image_in_empty_n, "(port)image_in_empty_n");
    sc_trace(mVcdFile, image_in_read, "(port)image_in_read");
    sc_trace(mVcdFile, img_rows_V_dout, "(port)img_rows_V_dout");
    sc_trace(mVcdFile, img_rows_V_empty_n, "(port)img_rows_V_empty_n");
    sc_trace(mVcdFile, img_rows_V_read, "(port)img_rows_V_read");
    sc_trace(mVcdFile, img_cols_V_dout, "(port)img_cols_V_dout");
    sc_trace(mVcdFile, img_cols_V_empty_n, "(port)img_cols_V_empty_n");
    sc_trace(mVcdFile, img_cols_V_read, "(port)img_cols_V_read");
    sc_trace(mVcdFile, img_data_stream_V_din, "(port)img_data_stream_V_din");
    sc_trace(mVcdFile, img_data_stream_V_full_n, "(port)img_data_stream_V_full_n");
    sc_trace(mVcdFile, img_data_stream_V_write, "(port)img_data_stream_V_write");
    sc_trace(mVcdFile, img_rows_V_out_din, "(port)img_rows_V_out_din");
    sc_trace(mVcdFile, img_rows_V_out_full_n, "(port)img_rows_V_out_full_n");
    sc_trace(mVcdFile, img_rows_V_out_write, "(port)img_rows_V_out_write");
    sc_trace(mVcdFile, img_cols_V_out_din, "(port)img_cols_V_out_din");
    sc_trace(mVcdFile, img_cols_V_out_full_n, "(port)img_cols_V_out_full_n");
    sc_trace(mVcdFile, img_cols_V_out_write, "(port)img_cols_V_out_write");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_bdd_21, "ap_sig_bdd_21");
    sc_trace(mVcdFile, image_in_read_reg_88, "image_in_read_reg_88");
    sc_trace(mVcdFile, ap_sig_bdd_123, "ap_sig_bdd_123");
    sc_trace(mVcdFile, img_rows_V_read_reg_93, "img_rows_V_read_reg_93");
    sc_trace(mVcdFile, img_cols_V_read_reg_98, "img_cols_V_read_reg_98");
    sc_trace(mVcdFile, grp_blur_Array2Mat_fu_74_ap_start, "grp_blur_Array2Mat_fu_74_ap_start");
    sc_trace(mVcdFile, grp_blur_Array2Mat_fu_74_ap_done, "grp_blur_Array2Mat_fu_74_ap_done");
    sc_trace(mVcdFile, grp_blur_Array2Mat_fu_74_ap_idle, "grp_blur_Array2Mat_fu_74_ap_idle");
    sc_trace(mVcdFile, grp_blur_Array2Mat_fu_74_ap_ready, "grp_blur_Array2Mat_fu_74_ap_ready");
    sc_trace(mVcdFile, grp_blur_Array2Mat_fu_74_m_axi_fb_AWVALID, "grp_blur_Array2Mat_fu_74_m_axi_fb_AWVALID");
    sc_trace(mVcdFile, grp_blur_Array2Mat_fu_74_m_axi_fb_AWREADY, "grp_blur_Array2Mat_fu_74_m_axi_fb_AWREADY");
    sc_trace(mVcdFile, grp_blur_Array2Mat_fu_74_m_axi_fb_AWADDR, "grp_blur_Array2Mat_fu_74_m_axi_fb_AWADDR");
    sc_trace(mVcdFile, grp_blur_Array2Mat_fu_74_m_axi_fb_AWID, "grp_blur_Array2Mat_fu_74_m_axi_fb_AWID");
    sc_trace(mVcdFile, grp_blur_Array2Mat_fu_74_m_axi_fb_AWLEN, "grp_blur_Array2Mat_fu_74_m_axi_fb_AWLEN");
    sc_trace(mVcdFile, grp_blur_Array2Mat_fu_74_m_axi_fb_AWSIZE, "grp_blur_Array2Mat_fu_74_m_axi_fb_AWSIZE");
    sc_trace(mVcdFile, grp_blur_Array2Mat_fu_74_m_axi_fb_AWBURST, "grp_blur_Array2Mat_fu_74_m_axi_fb_AWBURST");
    sc_trace(mVcdFile, grp_blur_Array2Mat_fu_74_m_axi_fb_AWLOCK, "grp_blur_Array2Mat_fu_74_m_axi_fb_AWLOCK");
    sc_trace(mVcdFile, grp_blur_Array2Mat_fu_74_m_axi_fb_AWCACHE, "grp_blur_Array2Mat_fu_74_m_axi_fb_AWCACHE");
    sc_trace(mVcdFile, grp_blur_Array2Mat_fu_74_m_axi_fb_AWPROT, "grp_blur_Array2Mat_fu_74_m_axi_fb_AWPROT");
    sc_trace(mVcdFile, grp_blur_Array2Mat_fu_74_m_axi_fb_AWQOS, "grp_blur_Array2Mat_fu_74_m_axi_fb_AWQOS");
    sc_trace(mVcdFile, grp_blur_Array2Mat_fu_74_m_axi_fb_AWREGION, "grp_blur_Array2Mat_fu_74_m_axi_fb_AWREGION");
    sc_trace(mVcdFile, grp_blur_Array2Mat_fu_74_m_axi_fb_AWUSER, "grp_blur_Array2Mat_fu_74_m_axi_fb_AWUSER");
    sc_trace(mVcdFile, grp_blur_Array2Mat_fu_74_m_axi_fb_WVALID, "grp_blur_Array2Mat_fu_74_m_axi_fb_WVALID");
    sc_trace(mVcdFile, grp_blur_Array2Mat_fu_74_m_axi_fb_WREADY, "grp_blur_Array2Mat_fu_74_m_axi_fb_WREADY");
    sc_trace(mVcdFile, grp_blur_Array2Mat_fu_74_m_axi_fb_WDATA, "grp_blur_Array2Mat_fu_74_m_axi_fb_WDATA");
    sc_trace(mVcdFile, grp_blur_Array2Mat_fu_74_m_axi_fb_WSTRB, "grp_blur_Array2Mat_fu_74_m_axi_fb_WSTRB");
    sc_trace(mVcdFile, grp_blur_Array2Mat_fu_74_m_axi_fb_WLAST, "grp_blur_Array2Mat_fu_74_m_axi_fb_WLAST");
    sc_trace(mVcdFile, grp_blur_Array2Mat_fu_74_m_axi_fb_WID, "grp_blur_Array2Mat_fu_74_m_axi_fb_WID");
    sc_trace(mVcdFile, grp_blur_Array2Mat_fu_74_m_axi_fb_WUSER, "grp_blur_Array2Mat_fu_74_m_axi_fb_WUSER");
    sc_trace(mVcdFile, grp_blur_Array2Mat_fu_74_m_axi_fb_ARVALID, "grp_blur_Array2Mat_fu_74_m_axi_fb_ARVALID");
    sc_trace(mVcdFile, grp_blur_Array2Mat_fu_74_m_axi_fb_ARREADY, "grp_blur_Array2Mat_fu_74_m_axi_fb_ARREADY");
    sc_trace(mVcdFile, grp_blur_Array2Mat_fu_74_m_axi_fb_ARADDR, "grp_blur_Array2Mat_fu_74_m_axi_fb_ARADDR");
    sc_trace(mVcdFile, grp_blur_Array2Mat_fu_74_m_axi_fb_ARID, "grp_blur_Array2Mat_fu_74_m_axi_fb_ARID");
    sc_trace(mVcdFile, grp_blur_Array2Mat_fu_74_m_axi_fb_ARLEN, "grp_blur_Array2Mat_fu_74_m_axi_fb_ARLEN");
    sc_trace(mVcdFile, grp_blur_Array2Mat_fu_74_m_axi_fb_ARSIZE, "grp_blur_Array2Mat_fu_74_m_axi_fb_ARSIZE");
    sc_trace(mVcdFile, grp_blur_Array2Mat_fu_74_m_axi_fb_ARBURST, "grp_blur_Array2Mat_fu_74_m_axi_fb_ARBURST");
    sc_trace(mVcdFile, grp_blur_Array2Mat_fu_74_m_axi_fb_ARLOCK, "grp_blur_Array2Mat_fu_74_m_axi_fb_ARLOCK");
    sc_trace(mVcdFile, grp_blur_Array2Mat_fu_74_m_axi_fb_ARCACHE, "grp_blur_Array2Mat_fu_74_m_axi_fb_ARCACHE");
    sc_trace(mVcdFile, grp_blur_Array2Mat_fu_74_m_axi_fb_ARPROT, "grp_blur_Array2Mat_fu_74_m_axi_fb_ARPROT");
    sc_trace(mVcdFile, grp_blur_Array2Mat_fu_74_m_axi_fb_ARQOS, "grp_blur_Array2Mat_fu_74_m_axi_fb_ARQOS");
    sc_trace(mVcdFile, grp_blur_Array2Mat_fu_74_m_axi_fb_ARREGION, "grp_blur_Array2Mat_fu_74_m_axi_fb_ARREGION");
    sc_trace(mVcdFile, grp_blur_Array2Mat_fu_74_m_axi_fb_ARUSER, "grp_blur_Array2Mat_fu_74_m_axi_fb_ARUSER");
    sc_trace(mVcdFile, grp_blur_Array2Mat_fu_74_m_axi_fb_RVALID, "grp_blur_Array2Mat_fu_74_m_axi_fb_RVALID");
    sc_trace(mVcdFile, grp_blur_Array2Mat_fu_74_m_axi_fb_RREADY, "grp_blur_Array2Mat_fu_74_m_axi_fb_RREADY");
    sc_trace(mVcdFile, grp_blur_Array2Mat_fu_74_m_axi_fb_RDATA, "grp_blur_Array2Mat_fu_74_m_axi_fb_RDATA");
    sc_trace(mVcdFile, grp_blur_Array2Mat_fu_74_m_axi_fb_RLAST, "grp_blur_Array2Mat_fu_74_m_axi_fb_RLAST");
    sc_trace(mVcdFile, grp_blur_Array2Mat_fu_74_m_axi_fb_RID, "grp_blur_Array2Mat_fu_74_m_axi_fb_RID");
    sc_trace(mVcdFile, grp_blur_Array2Mat_fu_74_m_axi_fb_RUSER, "grp_blur_Array2Mat_fu_74_m_axi_fb_RUSER");
    sc_trace(mVcdFile, grp_blur_Array2Mat_fu_74_m_axi_fb_RRESP, "grp_blur_Array2Mat_fu_74_m_axi_fb_RRESP");
    sc_trace(mVcdFile, grp_blur_Array2Mat_fu_74_m_axi_fb_BVALID, "grp_blur_Array2Mat_fu_74_m_axi_fb_BVALID");
    sc_trace(mVcdFile, grp_blur_Array2Mat_fu_74_m_axi_fb_BREADY, "grp_blur_Array2Mat_fu_74_m_axi_fb_BREADY");
    sc_trace(mVcdFile, grp_blur_Array2Mat_fu_74_m_axi_fb_BRESP, "grp_blur_Array2Mat_fu_74_m_axi_fb_BRESP");
    sc_trace(mVcdFile, grp_blur_Array2Mat_fu_74_m_axi_fb_BID, "grp_blur_Array2Mat_fu_74_m_axi_fb_BID");
    sc_trace(mVcdFile, grp_blur_Array2Mat_fu_74_m_axi_fb_BUSER, "grp_blur_Array2Mat_fu_74_m_axi_fb_BUSER");
    sc_trace(mVcdFile, grp_blur_Array2Mat_fu_74_image_in1, "grp_blur_Array2Mat_fu_74_image_in1");
    sc_trace(mVcdFile, grp_blur_Array2Mat_fu_74_img_rows_V_read, "grp_blur_Array2Mat_fu_74_img_rows_V_read");
    sc_trace(mVcdFile, grp_blur_Array2Mat_fu_74_img_cols_V_read, "grp_blur_Array2Mat_fu_74_img_cols_V_read");
    sc_trace(mVcdFile, grp_blur_Array2Mat_fu_74_img_data_stream_V_din, "grp_blur_Array2Mat_fu_74_img_data_stream_V_din");
    sc_trace(mVcdFile, grp_blur_Array2Mat_fu_74_img_data_stream_V_full_n, "grp_blur_Array2Mat_fu_74_img_data_stream_V_full_n");
    sc_trace(mVcdFile, grp_blur_Array2Mat_fu_74_img_data_stream_V_write, "grp_blur_Array2Mat_fu_74_img_data_stream_V_write");
    sc_trace(mVcdFile, grp_blur_Array2Mat_fu_74_ap_start_ap_start_reg, "grp_blur_Array2Mat_fu_74_ap_start_ap_start_reg");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st2_fsm_1, "ap_sig_cseq_ST_st2_fsm_1");
    sc_trace(mVcdFile, ap_sig_bdd_194, "ap_sig_bdd_194");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

blur_AXIM2Mat::~blur_AXIM2Mat() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete grp_blur_Array2Mat_fu_74;
}

void blur_AXIM2Mat::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                    !esl_seteq<1,1,1>(ap_const_logic_0, grp_blur_Array2Mat_fu_74_ap_done.read()))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_blur_Array2Mat_fu_74_ap_start_ap_start_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
             !ap_sig_bdd_123.read())) {
            grp_blur_Array2Mat_fu_74_ap_start_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_blur_Array2Mat_fu_74_ap_ready.read())) {
            grp_blur_Array2Mat_fu_74_ap_start_ap_start_reg = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && !ap_sig_bdd_123.read())) {
        image_in_read_reg_88 = image_in_dout.read();
        img_cols_V_read_reg_98 = img_cols_V_dout.read();
        img_rows_V_read_reg_93 = img_rows_V_dout.read();
    }
}

void blur_AXIM2Mat::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_done_reg.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
          !esl_seteq<1,1,1>(ap_const_logic_0, grp_blur_Array2Mat_fu_74_ap_done.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void blur_AXIM2Mat::thread_ap_idle() {
    if ((!esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void blur_AXIM2Mat::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         !esl_seteq<1,1,1>(ap_const_logic_0, grp_blur_Array2Mat_fu_74_ap_done.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void blur_AXIM2Mat::thread_ap_sig_bdd_123() {
    ap_sig_bdd_123 = (esl_seteq<1,1,1>(image_in_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(img_rows_V_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(img_cols_V_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(img_rows_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(img_cols_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void blur_AXIM2Mat::thread_ap_sig_bdd_194() {
    ap_sig_bdd_194 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void blur_AXIM2Mat::thread_ap_sig_bdd_21() {
    ap_sig_bdd_21 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void blur_AXIM2Mat::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_bdd_21.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void blur_AXIM2Mat::thread_ap_sig_cseq_ST_st2_fsm_1() {
    if (ap_sig_bdd_194.read()) {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    }
}

void blur_AXIM2Mat::thread_grp_blur_Array2Mat_fu_74_ap_start() {
    grp_blur_Array2Mat_fu_74_ap_start = grp_blur_Array2Mat_fu_74_ap_start_ap_start_reg.read();
}

void blur_AXIM2Mat::thread_grp_blur_Array2Mat_fu_74_image_in1() {
    grp_blur_Array2Mat_fu_74_image_in1 = image_in_read_reg_88.read();
}

void blur_AXIM2Mat::thread_grp_blur_Array2Mat_fu_74_img_cols_V_read() {
    grp_blur_Array2Mat_fu_74_img_cols_V_read = img_cols_V_read_reg_98.read();
}

void blur_AXIM2Mat::thread_grp_blur_Array2Mat_fu_74_img_data_stream_V_full_n() {
    grp_blur_Array2Mat_fu_74_img_data_stream_V_full_n = img_data_stream_V_full_n.read();
}

void blur_AXIM2Mat::thread_grp_blur_Array2Mat_fu_74_img_rows_V_read() {
    grp_blur_Array2Mat_fu_74_img_rows_V_read = img_rows_V_read_reg_93.read();
}

void blur_AXIM2Mat::thread_grp_blur_Array2Mat_fu_74_m_axi_fb_ARREADY() {
    grp_blur_Array2Mat_fu_74_m_axi_fb_ARREADY = m_axi_fb_ARREADY.read();
}

void blur_AXIM2Mat::thread_grp_blur_Array2Mat_fu_74_m_axi_fb_AWREADY() {
    grp_blur_Array2Mat_fu_74_m_axi_fb_AWREADY = ap_const_logic_0;
}

void blur_AXIM2Mat::thread_grp_blur_Array2Mat_fu_74_m_axi_fb_BID() {
    grp_blur_Array2Mat_fu_74_m_axi_fb_BID = ap_const_lv1_0;
}

void blur_AXIM2Mat::thread_grp_blur_Array2Mat_fu_74_m_axi_fb_BRESP() {
    grp_blur_Array2Mat_fu_74_m_axi_fb_BRESP = ap_const_lv2_0;
}

void blur_AXIM2Mat::thread_grp_blur_Array2Mat_fu_74_m_axi_fb_BUSER() {
    grp_blur_Array2Mat_fu_74_m_axi_fb_BUSER = ap_const_lv1_0;
}

void blur_AXIM2Mat::thread_grp_blur_Array2Mat_fu_74_m_axi_fb_BVALID() {
    grp_blur_Array2Mat_fu_74_m_axi_fb_BVALID = ap_const_logic_0;
}

void blur_AXIM2Mat::thread_grp_blur_Array2Mat_fu_74_m_axi_fb_RDATA() {
    grp_blur_Array2Mat_fu_74_m_axi_fb_RDATA = m_axi_fb_RDATA.read();
}

void blur_AXIM2Mat::thread_grp_blur_Array2Mat_fu_74_m_axi_fb_RID() {
    grp_blur_Array2Mat_fu_74_m_axi_fb_RID = m_axi_fb_RID.read();
}

void blur_AXIM2Mat::thread_grp_blur_Array2Mat_fu_74_m_axi_fb_RLAST() {
    grp_blur_Array2Mat_fu_74_m_axi_fb_RLAST = m_axi_fb_RLAST.read();
}

void blur_AXIM2Mat::thread_grp_blur_Array2Mat_fu_74_m_axi_fb_RRESP() {
    grp_blur_Array2Mat_fu_74_m_axi_fb_RRESP = m_axi_fb_RRESP.read();
}

void blur_AXIM2Mat::thread_grp_blur_Array2Mat_fu_74_m_axi_fb_RUSER() {
    grp_blur_Array2Mat_fu_74_m_axi_fb_RUSER = m_axi_fb_RUSER.read();
}

void blur_AXIM2Mat::thread_grp_blur_Array2Mat_fu_74_m_axi_fb_RVALID() {
    grp_blur_Array2Mat_fu_74_m_axi_fb_RVALID = m_axi_fb_RVALID.read();
}

void blur_AXIM2Mat::thread_grp_blur_Array2Mat_fu_74_m_axi_fb_WREADY() {
    grp_blur_Array2Mat_fu_74_m_axi_fb_WREADY = ap_const_logic_0;
}

void blur_AXIM2Mat::thread_image_in_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
         !ap_sig_bdd_123.read())) {
        image_in_read = ap_const_logic_1;
    } else {
        image_in_read = ap_const_logic_0;
    }
}

void blur_AXIM2Mat::thread_img_cols_V_out_din() {
    img_cols_V_out_din = img_cols_V_dout.read();
}

void blur_AXIM2Mat::thread_img_cols_V_out_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
         !ap_sig_bdd_123.read())) {
        img_cols_V_out_write = ap_const_logic_1;
    } else {
        img_cols_V_out_write = ap_const_logic_0;
    }
}

void blur_AXIM2Mat::thread_img_cols_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
         !ap_sig_bdd_123.read())) {
        img_cols_V_read = ap_const_logic_1;
    } else {
        img_cols_V_read = ap_const_logic_0;
    }
}

void blur_AXIM2Mat::thread_img_data_stream_V_din() {
    img_data_stream_V_din = grp_blur_Array2Mat_fu_74_img_data_stream_V_din.read();
}

void blur_AXIM2Mat::thread_img_data_stream_V_write() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        img_data_stream_V_write = grp_blur_Array2Mat_fu_74_img_data_stream_V_write.read();
    } else {
        img_data_stream_V_write = ap_const_logic_0;
    }
}

void blur_AXIM2Mat::thread_img_rows_V_out_din() {
    img_rows_V_out_din = img_rows_V_dout.read();
}

void blur_AXIM2Mat::thread_img_rows_V_out_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
         !ap_sig_bdd_123.read())) {
        img_rows_V_out_write = ap_const_logic_1;
    } else {
        img_rows_V_out_write = ap_const_logic_0;
    }
}

void blur_AXIM2Mat::thread_img_rows_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
         !ap_sig_bdd_123.read())) {
        img_rows_V_read = ap_const_logic_1;
    } else {
        img_rows_V_read = ap_const_logic_0;
    }
}

void blur_AXIM2Mat::thread_m_axi_fb_ARADDR() {
    m_axi_fb_ARADDR = grp_blur_Array2Mat_fu_74_m_axi_fb_ARADDR.read();
}

void blur_AXIM2Mat::thread_m_axi_fb_ARBURST() {
    m_axi_fb_ARBURST = grp_blur_Array2Mat_fu_74_m_axi_fb_ARBURST.read();
}

void blur_AXIM2Mat::thread_m_axi_fb_ARCACHE() {
    m_axi_fb_ARCACHE = grp_blur_Array2Mat_fu_74_m_axi_fb_ARCACHE.read();
}

void blur_AXIM2Mat::thread_m_axi_fb_ARID() {
    m_axi_fb_ARID = grp_blur_Array2Mat_fu_74_m_axi_fb_ARID.read();
}

void blur_AXIM2Mat::thread_m_axi_fb_ARLEN() {
    m_axi_fb_ARLEN = grp_blur_Array2Mat_fu_74_m_axi_fb_ARLEN.read();
}

void blur_AXIM2Mat::thread_m_axi_fb_ARLOCK() {
    m_axi_fb_ARLOCK = grp_blur_Array2Mat_fu_74_m_axi_fb_ARLOCK.read();
}

void blur_AXIM2Mat::thread_m_axi_fb_ARPROT() {
    m_axi_fb_ARPROT = grp_blur_Array2Mat_fu_74_m_axi_fb_ARPROT.read();
}

void blur_AXIM2Mat::thread_m_axi_fb_ARQOS() {
    m_axi_fb_ARQOS = grp_blur_Array2Mat_fu_74_m_axi_fb_ARQOS.read();
}

void blur_AXIM2Mat::thread_m_axi_fb_ARREGION() {
    m_axi_fb_ARREGION = grp_blur_Array2Mat_fu_74_m_axi_fb_ARREGION.read();
}

void blur_AXIM2Mat::thread_m_axi_fb_ARSIZE() {
    m_axi_fb_ARSIZE = grp_blur_Array2Mat_fu_74_m_axi_fb_ARSIZE.read();
}

void blur_AXIM2Mat::thread_m_axi_fb_ARUSER() {
    m_axi_fb_ARUSER = grp_blur_Array2Mat_fu_74_m_axi_fb_ARUSER.read();
}

void blur_AXIM2Mat::thread_m_axi_fb_ARVALID() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()))) {
        m_axi_fb_ARVALID = grp_blur_Array2Mat_fu_74_m_axi_fb_ARVALID.read();
    } else {
        m_axi_fb_ARVALID = ap_const_logic_0;
    }
}

void blur_AXIM2Mat::thread_m_axi_fb_AWADDR() {
    m_axi_fb_AWADDR = ap_const_lv32_0;
}

void blur_AXIM2Mat::thread_m_axi_fb_AWBURST() {
    m_axi_fb_AWBURST = ap_const_lv2_0;
}

void blur_AXIM2Mat::thread_m_axi_fb_AWCACHE() {
    m_axi_fb_AWCACHE = ap_const_lv4_0;
}

void blur_AXIM2Mat::thread_m_axi_fb_AWID() {
    m_axi_fb_AWID = ap_const_lv1_0;
}

void blur_AXIM2Mat::thread_m_axi_fb_AWLEN() {
    m_axi_fb_AWLEN = ap_const_lv32_0;
}

void blur_AXIM2Mat::thread_m_axi_fb_AWLOCK() {
    m_axi_fb_AWLOCK = ap_const_lv2_0;
}

void blur_AXIM2Mat::thread_m_axi_fb_AWPROT() {
    m_axi_fb_AWPROT = ap_const_lv3_0;
}

void blur_AXIM2Mat::thread_m_axi_fb_AWQOS() {
    m_axi_fb_AWQOS = ap_const_lv4_0;
}

void blur_AXIM2Mat::thread_m_axi_fb_AWREGION() {
    m_axi_fb_AWREGION = ap_const_lv4_0;
}

void blur_AXIM2Mat::thread_m_axi_fb_AWSIZE() {
    m_axi_fb_AWSIZE = ap_const_lv3_0;
}

void blur_AXIM2Mat::thread_m_axi_fb_AWUSER() {
    m_axi_fb_AWUSER = ap_const_lv1_0;
}

void blur_AXIM2Mat::thread_m_axi_fb_AWVALID() {
    m_axi_fb_AWVALID = ap_const_logic_0;
}

void blur_AXIM2Mat::thread_m_axi_fb_BREADY() {
    m_axi_fb_BREADY = ap_const_logic_0;
}

void blur_AXIM2Mat::thread_m_axi_fb_RREADY() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()))) {
        m_axi_fb_RREADY = grp_blur_Array2Mat_fu_74_m_axi_fb_RREADY.read();
    } else {
        m_axi_fb_RREADY = ap_const_logic_0;
    }
}

void blur_AXIM2Mat::thread_m_axi_fb_WDATA() {
    m_axi_fb_WDATA = ap_const_lv8_0;
}

void blur_AXIM2Mat::thread_m_axi_fb_WID() {
    m_axi_fb_WID = ap_const_lv1_0;
}

void blur_AXIM2Mat::thread_m_axi_fb_WLAST() {
    m_axi_fb_WLAST = ap_const_logic_0;
}

void blur_AXIM2Mat::thread_m_axi_fb_WSTRB() {
    m_axi_fb_WSTRB = ap_const_lv1_0;
}

void blur_AXIM2Mat::thread_m_axi_fb_WUSER() {
    m_axi_fb_WUSER = ap_const_lv1_0;
}

void blur_AXIM2Mat::thread_m_axi_fb_WVALID() {
    m_axi_fb_WVALID = ap_const_logic_0;
}

void blur_AXIM2Mat::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!ap_sig_bdd_123.read()) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            if (!esl_seteq<1,1,1>(ap_const_logic_0, grp_blur_Array2Mat_fu_74_ap_done.read())) {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            } else {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            }
            break;
        default : 
            ap_NS_fsm = "XX";
            break;
    }
}

}

