// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#include "blur_Mat2Array.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic blur_Mat2Array::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic blur_Mat2Array::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<9> blur_Mat2Array::ap_ST_st1_fsm_0 = "1";
const sc_lv<9> blur_Mat2Array::ap_ST_st2_fsm_1 = "10";
const sc_lv<9> blur_Mat2Array::ap_ST_st3_fsm_2 = "100";
const sc_lv<9> blur_Mat2Array::ap_ST_pp0_stg0_fsm_3 = "1000";
const sc_lv<9> blur_Mat2Array::ap_ST_st7_fsm_4 = "10000";
const sc_lv<9> blur_Mat2Array::ap_ST_st8_fsm_5 = "100000";
const sc_lv<9> blur_Mat2Array::ap_ST_st9_fsm_6 = "1000000";
const sc_lv<9> blur_Mat2Array::ap_ST_st10_fsm_7 = "10000000";
const sc_lv<9> blur_Mat2Array::ap_ST_st11_fsm_8 = "100000000";
const sc_lv<32> blur_Mat2Array::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> blur_Mat2Array::ap_const_lv1_1 = "1";
const sc_lv<1> blur_Mat2Array::ap_const_lv1_0 = "0";
const sc_lv<3> blur_Mat2Array::ap_const_lv3_0 = "000";
const sc_lv<2> blur_Mat2Array::ap_const_lv2_0 = "00";
const sc_lv<4> blur_Mat2Array::ap_const_lv4_0 = "0000";
const sc_lv<32> blur_Mat2Array::ap_const_lv32_1 = "1";
const sc_lv<32> blur_Mat2Array::ap_const_lv32_3 = "11";
const sc_lv<32> blur_Mat2Array::ap_const_lv32_2 = "10";
const sc_lv<11> blur_Mat2Array::ap_const_lv11_0 = "00000000000";
const sc_lv<32> blur_Mat2Array::ap_const_lv32_8 = "1000";
const sc_lv<32> blur_Mat2Array::ap_const_lv32_780 = "11110000000";
const sc_lv<11> blur_Mat2Array::ap_const_lv11_438 = "10000111000";
const sc_lv<11> blur_Mat2Array::ap_const_lv11_1 = "1";
const sc_lv<7> blur_Mat2Array::ap_const_lv7_0 = "0000000";
const sc_lv<11> blur_Mat2Array::ap_const_lv11_780 = "11110000000";

blur_Mat2Array::blur_Mat2Array(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( exitcond1_fu_125_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( exitcond1_fu_125_p2 );

    SC_METHOD(thread_ap_sig_bdd_106);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_120);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_127);
    sensitive << ( img_data_stream_V_empty_n );
    sensitive << ( exitcond_reg_220 );

    SC_METHOD(thread_ap_sig_bdd_155);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_174);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_27);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_291);
    sensitive << ( ap_reg_ppstg_exitcond_reg_220_pp0_it1 );
    sensitive << ( ap_reg_ppiten_pp0_it2 );

    SC_METHOD(thread_ap_sig_bdd_292);
    sensitive << ( m_axi_fb_WREADY );
    sensitive << ( ap_sig_bdd_127 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_ap_sig_cseq_ST_pp0_stg0_fsm_3);
    sensitive << ( ap_sig_bdd_120 );

    SC_METHOD(thread_ap_sig_cseq_ST_st11_fsm_8);
    sensitive << ( ap_sig_bdd_174 );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_bdd_27 );

    SC_METHOD(thread_ap_sig_cseq_ST_st2_fsm_1);
    sensitive << ( ap_sig_bdd_106 );

    SC_METHOD(thread_ap_sig_cseq_ST_st3_fsm_2);
    sensitive << ( ap_sig_bdd_155 );

    SC_METHOD(thread_ap_sig_ioackin_m_axi_fb_AWREADY);
    sensitive << ( m_axi_fb_AWREADY );
    sensitive << ( ap_reg_ioackin_m_axi_fb_AWREADY );

    SC_METHOD(thread_ap_sig_ioackin_m_axi_fb_WREADY);
    sensitive << ( m_axi_fb_WREADY );
    sensitive << ( ap_reg_ioackin_m_axi_fb_WREADY );

    SC_METHOD(thread_col_V_fu_196_p2);
    sensitive << ( p_1_reg_110 );

    SC_METHOD(thread_exitcond1_fu_125_p2);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( p_s_reg_99 );

    SC_METHOD(thread_exitcond_fu_190_p2);
    sensitive << ( p_1_reg_110 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_3 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_sig_bdd_127 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppstg_exitcond_reg_220_pp0_it1 );
    sensitive << ( ap_sig_ioackin_m_axi_fb_WREADY );
    sensitive << ( ap_reg_ppiten_pp0_it2 );

    SC_METHOD(thread_img_data_stream_V_read);
    sensitive << ( exitcond_reg_220 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_3 );
    sensitive << ( ap_sig_bdd_127 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppstg_exitcond_reg_220_pp0_it1 );
    sensitive << ( ap_sig_ioackin_m_axi_fb_WREADY );
    sensitive << ( ap_reg_ppiten_pp0_it2 );

    SC_METHOD(thread_m_axi_fb_ARADDR);

    SC_METHOD(thread_m_axi_fb_ARBURST);

    SC_METHOD(thread_m_axi_fb_ARCACHE);

    SC_METHOD(thread_m_axi_fb_ARID);

    SC_METHOD(thread_m_axi_fb_ARLEN);

    SC_METHOD(thread_m_axi_fb_ARLOCK);

    SC_METHOD(thread_m_axi_fb_ARPROT);

    SC_METHOD(thread_m_axi_fb_ARQOS);

    SC_METHOD(thread_m_axi_fb_ARREGION);

    SC_METHOD(thread_m_axi_fb_ARSIZE);

    SC_METHOD(thread_m_axi_fb_ARUSER);

    SC_METHOD(thread_m_axi_fb_ARVALID);

    SC_METHOD(thread_m_axi_fb_AWADDR);
    sensitive << ( fb_addr_reg_215 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( ap_reg_ioackin_m_axi_fb_AWREADY );

    SC_METHOD(thread_m_axi_fb_AWBURST);

    SC_METHOD(thread_m_axi_fb_AWCACHE);

    SC_METHOD(thread_m_axi_fb_AWID);

    SC_METHOD(thread_m_axi_fb_AWLEN);
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( ap_reg_ioackin_m_axi_fb_AWREADY );

    SC_METHOD(thread_m_axi_fb_AWLOCK);

    SC_METHOD(thread_m_axi_fb_AWPROT);

    SC_METHOD(thread_m_axi_fb_AWQOS);

    SC_METHOD(thread_m_axi_fb_AWREGION);

    SC_METHOD(thread_m_axi_fb_AWSIZE);

    SC_METHOD(thread_m_axi_fb_AWUSER);

    SC_METHOD(thread_m_axi_fb_AWVALID);
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( ap_reg_ioackin_m_axi_fb_AWREADY );

    SC_METHOD(thread_m_axi_fb_BREADY);
    sensitive << ( m_axi_fb_BVALID );
    sensitive << ( ap_sig_cseq_ST_st11_fsm_8 );

    SC_METHOD(thread_m_axi_fb_RREADY);

    SC_METHOD(thread_m_axi_fb_WDATA);
    sensitive << ( ap_sig_bdd_127 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppstg_exitcond_reg_220_pp0_it1 );
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( tmp_7_reg_229 );
    sensitive << ( ap_reg_ioackin_m_axi_fb_WREADY );

    SC_METHOD(thread_m_axi_fb_WID);

    SC_METHOD(thread_m_axi_fb_WLAST);

    SC_METHOD(thread_m_axi_fb_WSTRB);
    sensitive << ( ap_sig_bdd_127 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppstg_exitcond_reg_220_pp0_it1 );
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( ap_reg_ioackin_m_axi_fb_WREADY );

    SC_METHOD(thread_m_axi_fb_WUSER);

    SC_METHOD(thread_m_axi_fb_WVALID);
    sensitive << ( ap_sig_bdd_127 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppstg_exitcond_reg_220_pp0_it1 );
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( ap_reg_ioackin_m_axi_fb_WREADY );

    SC_METHOD(thread_p_shl2_cast_fu_157_p1);
    sensitive << ( p_shl2_fu_149_p3 );

    SC_METHOD(thread_p_shl2_fu_149_p3);
    sensitive << ( p_s_reg_99 );

    SC_METHOD(thread_p_shl_cast_fu_145_p1);
    sensitive << ( p_shl_fu_137_p3 );

    SC_METHOD(thread_p_shl_fu_137_p3);
    sensitive << ( p_s_reg_99 );

    SC_METHOD(thread_r_V_cast_fu_167_p1);
    sensitive << ( r_V_fu_161_p2 );

    SC_METHOD(thread_r_V_fu_161_p2);
    sensitive << ( p_shl_cast_fu_145_p1 );
    sensitive << ( p_shl2_cast_fu_157_p1 );

    SC_METHOD(thread_row_V_fu_131_p2);
    sensitive << ( p_s_reg_99 );

    SC_METHOD(thread_sext_cast_fu_121_p1);
    sensitive << ( image_out1 );

    SC_METHOD(thread_tmp_1_fu_171_p1);
    sensitive << ( r_V_cast_fu_167_p1 );

    SC_METHOD(thread_tmp_4_fu_175_p2);
    sensitive << ( sext_cast_reg_202 );
    sensitive << ( tmp_1_fu_171_p1 );

    SC_METHOD(thread_tmp_5_fu_180_p1);
    sensitive << ( tmp_4_fu_175_p2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( m_axi_fb_BVALID );
    sensitive << ( exitcond1_fu_125_p2 );
    sensitive << ( exitcond_fu_190_p2 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_sig_bdd_127 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppstg_exitcond_reg_220_pp0_it1 );
    sensitive << ( ap_sig_ioackin_m_axi_fb_WREADY );
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( ap_sig_ioackin_m_axi_fb_AWREADY );

    ap_CS_fsm = "000000001";
    ap_reg_ppiten_pp0_it0 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it1 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it2 = SC_LOGIC_0;
    ap_reg_ioackin_m_axi_fb_AWREADY = SC_LOGIC_0;
    ap_reg_ioackin_m_axi_fb_WREADY = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "blur_Mat2Array_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, img_data_stream_V_dout, "(port)img_data_stream_V_dout");
    sc_trace(mVcdFile, img_data_stream_V_empty_n, "(port)img_data_stream_V_empty_n");
    sc_trace(mVcdFile, img_data_stream_V_read, "(port)img_data_stream_V_read");
    sc_trace(mVcdFile, m_axi_fb_AWVALID, "(port)m_axi_fb_AWVALID");
    sc_trace(mVcdFile, m_axi_fb_AWREADY, "(port)m_axi_fb_AWREADY");
    sc_trace(mVcdFile, m_axi_fb_AWADDR, "(port)m_axi_fb_AWADDR");
    sc_trace(mVcdFile, m_axi_fb_AWID, "(port)m_axi_fb_AWID");
    sc_trace(mVcdFile, m_axi_fb_AWLEN, "(port)m_axi_fb_AWLEN");
    sc_trace(mVcdFile, m_axi_fb_AWSIZE, "(port)m_axi_fb_AWSIZE");
    sc_trace(mVcdFile, m_axi_fb_AWBURST, "(port)m_axi_fb_AWBURST");
    sc_trace(mVcdFile, m_axi_fb_AWLOCK, "(port)m_axi_fb_AWLOCK");
    sc_trace(mVcdFile, m_axi_fb_AWCACHE, "(port)m_axi_fb_AWCACHE");
    sc_trace(mVcdFile, m_axi_fb_AWPROT, "(port)m_axi_fb_AWPROT");
    sc_trace(mVcdFile, m_axi_fb_AWQOS, "(port)m_axi_fb_AWQOS");
    sc_trace(mVcdFile, m_axi_fb_AWREGION, "(port)m_axi_fb_AWREGION");
    sc_trace(mVcdFile, m_axi_fb_AWUSER, "(port)m_axi_fb_AWUSER");
    sc_trace(mVcdFile, m_axi_fb_WVALID, "(port)m_axi_fb_WVALID");
    sc_trace(mVcdFile, m_axi_fb_WREADY, "(port)m_axi_fb_WREADY");
    sc_trace(mVcdFile, m_axi_fb_WDATA, "(port)m_axi_fb_WDATA");
    sc_trace(mVcdFile, m_axi_fb_WSTRB, "(port)m_axi_fb_WSTRB");
    sc_trace(mVcdFile, m_axi_fb_WLAST, "(port)m_axi_fb_WLAST");
    sc_trace(mVcdFile, m_axi_fb_WID, "(port)m_axi_fb_WID");
    sc_trace(mVcdFile, m_axi_fb_WUSER, "(port)m_axi_fb_WUSER");
    sc_trace(mVcdFile, m_axi_fb_ARVALID, "(port)m_axi_fb_ARVALID");
    sc_trace(mVcdFile, m_axi_fb_ARREADY, "(port)m_axi_fb_ARREADY");
    sc_trace(mVcdFile, m_axi_fb_ARADDR, "(port)m_axi_fb_ARADDR");
    sc_trace(mVcdFile, m_axi_fb_ARID, "(port)m_axi_fb_ARID");
    sc_trace(mVcdFile, m_axi_fb_ARLEN, "(port)m_axi_fb_ARLEN");
    sc_trace(mVcdFile, m_axi_fb_ARSIZE, "(port)m_axi_fb_ARSIZE");
    sc_trace(mVcdFile, m_axi_fb_ARBURST, "(port)m_axi_fb_ARBURST");
    sc_trace(mVcdFile, m_axi_fb_ARLOCK, "(port)m_axi_fb_ARLOCK");
    sc_trace(mVcdFile, m_axi_fb_ARCACHE, "(port)m_axi_fb_ARCACHE");
    sc_trace(mVcdFile, m_axi_fb_ARPROT, "(port)m_axi_fb_ARPROT");
    sc_trace(mVcdFile, m_axi_fb_ARQOS, "(port)m_axi_fb_ARQOS");
    sc_trace(mVcdFile, m_axi_fb_ARREGION, "(port)m_axi_fb_ARREGION");
    sc_trace(mVcdFile, m_axi_fb_ARUSER, "(port)m_axi_fb_ARUSER");
    sc_trace(mVcdFile, m_axi_fb_RVALID, "(port)m_axi_fb_RVALID");
    sc_trace(mVcdFile, m_axi_fb_RREADY, "(port)m_axi_fb_RREADY");
    sc_trace(mVcdFile, m_axi_fb_RDATA, "(port)m_axi_fb_RDATA");
    sc_trace(mVcdFile, m_axi_fb_RLAST, "(port)m_axi_fb_RLAST");
    sc_trace(mVcdFile, m_axi_fb_RID, "(port)m_axi_fb_RID");
    sc_trace(mVcdFile, m_axi_fb_RUSER, "(port)m_axi_fb_RUSER");
    sc_trace(mVcdFile, m_axi_fb_RRESP, "(port)m_axi_fb_RRESP");
    sc_trace(mVcdFile, m_axi_fb_BVALID, "(port)m_axi_fb_BVALID");
    sc_trace(mVcdFile, m_axi_fb_BREADY, "(port)m_axi_fb_BREADY");
    sc_trace(mVcdFile, m_axi_fb_BRESP, "(port)m_axi_fb_BRESP");
    sc_trace(mVcdFile, m_axi_fb_BID, "(port)m_axi_fb_BID");
    sc_trace(mVcdFile, m_axi_fb_BUSER, "(port)m_axi_fb_BUSER");
    sc_trace(mVcdFile, image_out1, "(port)image_out1");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_bdd_27, "ap_sig_bdd_27");
    sc_trace(mVcdFile, p_1_reg_110, "p_1_reg_110");
    sc_trace(mVcdFile, sext_cast_fu_121_p1, "sext_cast_fu_121_p1");
    sc_trace(mVcdFile, sext_cast_reg_202, "sext_cast_reg_202");
    sc_trace(mVcdFile, row_V_fu_131_p2, "row_V_fu_131_p2");
    sc_trace(mVcdFile, row_V_reg_210, "row_V_reg_210");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st2_fsm_1, "ap_sig_cseq_ST_st2_fsm_1");
    sc_trace(mVcdFile, ap_sig_bdd_106, "ap_sig_bdd_106");
    sc_trace(mVcdFile, fb_addr_reg_215, "fb_addr_reg_215");
    sc_trace(mVcdFile, exitcond1_fu_125_p2, "exitcond1_fu_125_p2");
    sc_trace(mVcdFile, exitcond_fu_190_p2, "exitcond_fu_190_p2");
    sc_trace(mVcdFile, exitcond_reg_220, "exitcond_reg_220");
    sc_trace(mVcdFile, ap_sig_cseq_ST_pp0_stg0_fsm_3, "ap_sig_cseq_ST_pp0_stg0_fsm_3");
    sc_trace(mVcdFile, ap_sig_bdd_120, "ap_sig_bdd_120");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it0, "ap_reg_ppiten_pp0_it0");
    sc_trace(mVcdFile, ap_sig_bdd_127, "ap_sig_bdd_127");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it1, "ap_reg_ppiten_pp0_it1");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_reg_220_pp0_it1, "ap_reg_ppstg_exitcond_reg_220_pp0_it1");
    sc_trace(mVcdFile, ap_sig_ioackin_m_axi_fb_WREADY, "ap_sig_ioackin_m_axi_fb_WREADY");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it2, "ap_reg_ppiten_pp0_it2");
    sc_trace(mVcdFile, col_V_fu_196_p2, "col_V_fu_196_p2");
    sc_trace(mVcdFile, tmp_7_reg_229, "tmp_7_reg_229");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st3_fsm_2, "ap_sig_cseq_ST_st3_fsm_2");
    sc_trace(mVcdFile, ap_sig_bdd_155, "ap_sig_bdd_155");
    sc_trace(mVcdFile, ap_sig_ioackin_m_axi_fb_AWREADY, "ap_sig_ioackin_m_axi_fb_AWREADY");
    sc_trace(mVcdFile, p_s_reg_99, "p_s_reg_99");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st11_fsm_8, "ap_sig_cseq_ST_st11_fsm_8");
    sc_trace(mVcdFile, ap_sig_bdd_174, "ap_sig_bdd_174");
    sc_trace(mVcdFile, tmp_5_fu_180_p1, "tmp_5_fu_180_p1");
    sc_trace(mVcdFile, ap_reg_ioackin_m_axi_fb_AWREADY, "ap_reg_ioackin_m_axi_fb_AWREADY");
    sc_trace(mVcdFile, ap_reg_ioackin_m_axi_fb_WREADY, "ap_reg_ioackin_m_axi_fb_WREADY");
    sc_trace(mVcdFile, p_shl_fu_137_p3, "p_shl_fu_137_p3");
    sc_trace(mVcdFile, p_shl2_fu_149_p3, "p_shl2_fu_149_p3");
    sc_trace(mVcdFile, p_shl_cast_fu_145_p1, "p_shl_cast_fu_145_p1");
    sc_trace(mVcdFile, p_shl2_cast_fu_157_p1, "p_shl2_cast_fu_157_p1");
    sc_trace(mVcdFile, r_V_fu_161_p2, "r_V_fu_161_p2");
    sc_trace(mVcdFile, r_V_cast_fu_167_p1, "r_V_cast_fu_167_p1");
    sc_trace(mVcdFile, tmp_1_fu_171_p1, "tmp_1_fu_171_p1");
    sc_trace(mVcdFile, tmp_4_fu_175_p2, "tmp_4_fu_175_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_sig_bdd_292, "ap_sig_bdd_292");
    sc_trace(mVcdFile, ap_sig_bdd_291, "ap_sig_bdd_291");
#endif

    }
}

blur_Mat2Array::~blur_Mat2Array() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void blur_Mat2Array::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ioackin_m_axi_fb_AWREADY = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
            if (!esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_m_axi_fb_AWREADY.read())) {
                ap_reg_ioackin_m_axi_fb_AWREADY = ap_const_logic_0;
            } else if (esl_seteq<1,1,1>(ap_const_logic_1, m_axi_fb_AWREADY.read())) {
                ap_reg_ioackin_m_axi_fb_AWREADY = ap_const_logic_1;
            }
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ioackin_m_axi_fb_WREADY = ap_const_logic_0;
    } else {
        if (ap_sig_bdd_291.read()) {
            if (!((ap_sig_bdd_127.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond_reg_220_pp0_it1.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_m_axi_fb_WREADY.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read())))) {
                ap_reg_ioackin_m_axi_fb_WREADY = ap_const_logic_0;
            } else if (ap_sig_bdd_292.read()) {
                ap_reg_ioackin_m_axi_fb_WREADY = ap_const_logic_1;
            }
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_3.read()) && 
             !((ap_sig_bdd_127.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond_reg_220_pp0_it1.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_m_axi_fb_WREADY.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()))) && 
             !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_190_p2.read()))) {
            ap_reg_ppiten_pp0_it0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
                    !esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_m_axi_fb_AWREADY.read()))) {
            ap_reg_ppiten_pp0_it0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_3.read()) && 
             !((ap_sig_bdd_127.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond_reg_220_pp0_it1.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_m_axi_fb_WREADY.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()))) && 
             esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_190_p2.read()))) {
            ap_reg_ppiten_pp0_it1 = ap_const_logic_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
                     !esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_m_axi_fb_AWREADY.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_3.read()) && 
                     !((ap_sig_bdd_127.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond_reg_220_pp0_it1.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_m_axi_fb_WREADY.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()))) && 
                     !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_190_p2.read())))) {
            ap_reg_ppiten_pp0_it1 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it2 = ap_const_logic_0;
    } else {
        if (!((ap_sig_bdd_127.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond_reg_220_pp0_it1.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_m_axi_fb_WREADY.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read())))) {
            ap_reg_ppiten_pp0_it2 = ap_reg_ppiten_pp0_it1.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
                    !esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_m_axi_fb_AWREADY.read()))) {
            ap_reg_ppiten_pp0_it2 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_3.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
         !((ap_sig_bdd_127.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond_reg_220_pp0_it1.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_m_axi_fb_WREADY.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()))) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_190_p2.read()))) {
        p_1_reg_110 = col_V_fu_196_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
                !esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_m_axi_fb_AWREADY.read()))) {
        p_1_reg_110 = ap_const_lv11_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_8.read()) && 
         !esl_seteq<1,1,1>(m_axi_fb_BVALID.read(), ap_const_logic_0))) {
        p_s_reg_99 = row_V_reg_210.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        p_s_reg_99 = ap_const_lv11_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_3.read()) && !((ap_sig_bdd_127.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond_reg_220_pp0_it1.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_m_axi_fb_WREADY.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()))))) {
        ap_reg_ppstg_exitcond_reg_220_pp0_it1 = exitcond_reg_220.read();
        exitcond_reg_220 = exitcond_fu_190_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_125_p2.read()))) {
        fb_addr_reg_215 =  (sc_lv<32>) (tmp_5_fu_180_p1.read());
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        row_V_reg_210 = row_V_fu_131_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        sext_cast_reg_202 = sext_cast_fu_121_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_3.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_220.read()) && !((ap_sig_bdd_127.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond_reg_220_pp0_it1.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_m_axi_fb_WREADY.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()))))) {
        tmp_7_reg_229 = img_data_stream_V_dout.read();
    }
}

void blur_Mat2Array::thread_ap_done() {
    if (((!esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_125_p2.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void blur_Mat2Array::thread_ap_idle() {
    if ((!esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void blur_Mat2Array::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_125_p2.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void blur_Mat2Array::thread_ap_sig_bdd_106() {
    ap_sig_bdd_106 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void blur_Mat2Array::thread_ap_sig_bdd_120() {
    ap_sig_bdd_120 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(3, 3));
}

void blur_Mat2Array::thread_ap_sig_bdd_127() {
    ap_sig_bdd_127 = (esl_seteq<1,1,1>(img_data_stream_V_empty_n.read(), ap_const_logic_0) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_220.read()));
}

void blur_Mat2Array::thread_ap_sig_bdd_155() {
    ap_sig_bdd_155 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(2, 2));
}

void blur_Mat2Array::thread_ap_sig_bdd_174() {
    ap_sig_bdd_174 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(8, 8));
}

void blur_Mat2Array::thread_ap_sig_bdd_27() {
    ap_sig_bdd_27 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void blur_Mat2Array::thread_ap_sig_bdd_291() {
    ap_sig_bdd_291 = (esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond_reg_220_pp0_it1.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()));
}

void blur_Mat2Array::thread_ap_sig_bdd_292() {
    ap_sig_bdd_292 = (esl_seteq<1,1,1>(ap_const_logic_1, m_axi_fb_WREADY.read()) && !(ap_sig_bdd_127.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())));
}

void blur_Mat2Array::thread_ap_sig_cseq_ST_pp0_stg0_fsm_3() {
    if (ap_sig_bdd_120.read()) {
        ap_sig_cseq_ST_pp0_stg0_fsm_3 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_pp0_stg0_fsm_3 = ap_const_logic_0;
    }
}

void blur_Mat2Array::thread_ap_sig_cseq_ST_st11_fsm_8() {
    if (ap_sig_bdd_174.read()) {
        ap_sig_cseq_ST_st11_fsm_8 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st11_fsm_8 = ap_const_logic_0;
    }
}

void blur_Mat2Array::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_bdd_27.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void blur_Mat2Array::thread_ap_sig_cseq_ST_st2_fsm_1() {
    if (ap_sig_bdd_106.read()) {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    }
}

void blur_Mat2Array::thread_ap_sig_cseq_ST_st3_fsm_2() {
    if (ap_sig_bdd_155.read()) {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_0;
    }
}

void blur_Mat2Array::thread_ap_sig_ioackin_m_axi_fb_AWREADY() {
    if (esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ioackin_m_axi_fb_AWREADY.read())) {
        ap_sig_ioackin_m_axi_fb_AWREADY = m_axi_fb_AWREADY.read();
    } else {
        ap_sig_ioackin_m_axi_fb_AWREADY = ap_const_logic_1;
    }
}

void blur_Mat2Array::thread_ap_sig_ioackin_m_axi_fb_WREADY() {
    if (esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ioackin_m_axi_fb_WREADY.read())) {
        ap_sig_ioackin_m_axi_fb_WREADY = m_axi_fb_WREADY.read();
    } else {
        ap_sig_ioackin_m_axi_fb_WREADY = ap_const_logic_1;
    }
}

void blur_Mat2Array::thread_col_V_fu_196_p2() {
    col_V_fu_196_p2 = (!p_1_reg_110.read().is_01() || !ap_const_lv11_1.is_01())? sc_lv<11>(): (sc_biguint<11>(p_1_reg_110.read()) + sc_biguint<11>(ap_const_lv11_1));
}

void blur_Mat2Array::thread_exitcond1_fu_125_p2() {
    exitcond1_fu_125_p2 = (!p_s_reg_99.read().is_01() || !ap_const_lv11_438.is_01())? sc_lv<1>(): sc_lv<1>(p_s_reg_99.read() == ap_const_lv11_438);
}

void blur_Mat2Array::thread_exitcond_fu_190_p2() {
    exitcond_fu_190_p2 = (!p_1_reg_110.read().is_01() || !ap_const_lv11_780.is_01())? sc_lv<1>(): sc_lv<1>(p_1_reg_110.read() == ap_const_lv11_780);
}

void blur_Mat2Array::thread_img_data_stream_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_220.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         !((ap_sig_bdd_127.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond_reg_220_pp0_it1.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_m_axi_fb_WREADY.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()))))) {
        img_data_stream_V_read = ap_const_logic_1;
    } else {
        img_data_stream_V_read = ap_const_logic_0;
    }
}

void blur_Mat2Array::thread_m_axi_fb_ARADDR() {
    m_axi_fb_ARADDR = ap_const_lv32_0;
}

void blur_Mat2Array::thread_m_axi_fb_ARBURST() {
    m_axi_fb_ARBURST = ap_const_lv2_0;
}

void blur_Mat2Array::thread_m_axi_fb_ARCACHE() {
    m_axi_fb_ARCACHE = ap_const_lv4_0;
}

void blur_Mat2Array::thread_m_axi_fb_ARID() {
    m_axi_fb_ARID = ap_const_lv1_0;
}

void blur_Mat2Array::thread_m_axi_fb_ARLEN() {
    m_axi_fb_ARLEN = ap_const_lv32_0;
}

void blur_Mat2Array::thread_m_axi_fb_ARLOCK() {
    m_axi_fb_ARLOCK = ap_const_lv2_0;
}

void blur_Mat2Array::thread_m_axi_fb_ARPROT() {
    m_axi_fb_ARPROT = ap_const_lv3_0;
}

void blur_Mat2Array::thread_m_axi_fb_ARQOS() {
    m_axi_fb_ARQOS = ap_const_lv4_0;
}

void blur_Mat2Array::thread_m_axi_fb_ARREGION() {
    m_axi_fb_ARREGION = ap_const_lv4_0;
}

void blur_Mat2Array::thread_m_axi_fb_ARSIZE() {
    m_axi_fb_ARSIZE = ap_const_lv3_0;
}

void blur_Mat2Array::thread_m_axi_fb_ARUSER() {
    m_axi_fb_ARUSER = ap_const_lv1_0;
}

void blur_Mat2Array::thread_m_axi_fb_ARVALID() {
    m_axi_fb_ARVALID = ap_const_logic_0;
}

void blur_Mat2Array::thread_m_axi_fb_AWADDR() {
    m_axi_fb_AWADDR = fb_addr_reg_215.read();
}

void blur_Mat2Array::thread_m_axi_fb_AWBURST() {
    m_axi_fb_AWBURST = ap_const_lv2_0;
}

void blur_Mat2Array::thread_m_axi_fb_AWCACHE() {
    m_axi_fb_AWCACHE = ap_const_lv4_0;
}

void blur_Mat2Array::thread_m_axi_fb_AWID() {
    m_axi_fb_AWID = ap_const_lv1_0;
}

void blur_Mat2Array::thread_m_axi_fb_AWLEN() {
    m_axi_fb_AWLEN = ap_const_lv32_780;
}

void blur_Mat2Array::thread_m_axi_fb_AWLOCK() {
    m_axi_fb_AWLOCK = ap_const_lv2_0;
}

void blur_Mat2Array::thread_m_axi_fb_AWPROT() {
    m_axi_fb_AWPROT = ap_const_lv3_0;
}

void blur_Mat2Array::thread_m_axi_fb_AWQOS() {
    m_axi_fb_AWQOS = ap_const_lv4_0;
}

void blur_Mat2Array::thread_m_axi_fb_AWREGION() {
    m_axi_fb_AWREGION = ap_const_lv4_0;
}

void blur_Mat2Array::thread_m_axi_fb_AWSIZE() {
    m_axi_fb_AWSIZE = ap_const_lv3_0;
}

void blur_Mat2Array::thread_m_axi_fb_AWUSER() {
    m_axi_fb_AWUSER = ap_const_lv1_0;
}

void blur_Mat2Array::thread_m_axi_fb_AWVALID() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ioackin_m_axi_fb_AWREADY.read()))) {
        m_axi_fb_AWVALID = ap_const_logic_1;
    } else {
        m_axi_fb_AWVALID = ap_const_logic_0;
    }
}

void blur_Mat2Array::thread_m_axi_fb_BREADY() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_8.read()) && 
         !esl_seteq<1,1,1>(m_axi_fb_BVALID.read(), ap_const_logic_0))) {
        m_axi_fb_BREADY = ap_const_logic_1;
    } else {
        m_axi_fb_BREADY = ap_const_logic_0;
    }
}

void blur_Mat2Array::thread_m_axi_fb_RREADY() {
    m_axi_fb_RREADY = ap_const_logic_0;
}

void blur_Mat2Array::thread_m_axi_fb_WDATA() {
    m_axi_fb_WDATA = tmp_7_reg_229.read();
}

void blur_Mat2Array::thread_m_axi_fb_WID() {
    m_axi_fb_WID = ap_const_lv1_0;
}

void blur_Mat2Array::thread_m_axi_fb_WLAST() {
    m_axi_fb_WLAST = ap_const_logic_0;
}

void blur_Mat2Array::thread_m_axi_fb_WSTRB() {
    m_axi_fb_WSTRB = ap_const_lv1_1;
}

void blur_Mat2Array::thread_m_axi_fb_WUSER() {
    m_axi_fb_WUSER = ap_const_lv1_0;
}

void blur_Mat2Array::thread_m_axi_fb_WVALID() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond_reg_220_pp0_it1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
         !(ap_sig_bdd_127.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ioackin_m_axi_fb_WREADY.read()))) {
        m_axi_fb_WVALID = ap_const_logic_1;
    } else {
        m_axi_fb_WVALID = ap_const_logic_0;
    }
}

void blur_Mat2Array::thread_p_shl2_cast_fu_157_p1() {
    p_shl2_cast_fu_157_p1 = esl_zext<23,18>(p_shl2_fu_149_p3.read());
}

void blur_Mat2Array::thread_p_shl2_fu_149_p3() {
    p_shl2_fu_149_p3 = esl_concat<11,7>(p_s_reg_99.read(), ap_const_lv7_0);
}

void blur_Mat2Array::thread_p_shl_cast_fu_145_p1() {
    p_shl_cast_fu_145_p1 = esl_zext<23,22>(p_shl_fu_137_p3.read());
}

void blur_Mat2Array::thread_p_shl_fu_137_p3() {
    p_shl_fu_137_p3 = esl_concat<11,11>(p_s_reg_99.read(), ap_const_lv11_0);
}

void blur_Mat2Array::thread_r_V_cast_fu_167_p1() {
    r_V_cast_fu_167_p1 = esl_sext<44,23>(r_V_fu_161_p2.read());
}

void blur_Mat2Array::thread_r_V_fu_161_p2() {
    r_V_fu_161_p2 = (!p_shl_cast_fu_145_p1.read().is_01() || !p_shl2_cast_fu_157_p1.read().is_01())? sc_lv<23>(): (sc_biguint<23>(p_shl_cast_fu_145_p1.read()) - sc_biguint<23>(p_shl2_cast_fu_157_p1.read()));
}

void blur_Mat2Array::thread_row_V_fu_131_p2() {
    row_V_fu_131_p2 = (!p_s_reg_99.read().is_01() || !ap_const_lv11_1.is_01())? sc_lv<11>(): (sc_biguint<11>(p_s_reg_99.read()) + sc_biguint<11>(ap_const_lv11_1));
}

void blur_Mat2Array::thread_sext_cast_fu_121_p1() {
    sext_cast_fu_121_p1 = esl_sext<46,32>(image_out1.read());
}

void blur_Mat2Array::thread_tmp_1_fu_171_p1() {
    tmp_1_fu_171_p1 = esl_zext<46,44>(r_V_cast_fu_167_p1.read());
}

void blur_Mat2Array::thread_tmp_4_fu_175_p2() {
    tmp_4_fu_175_p2 = (!sext_cast_reg_202.read().is_01() || !tmp_1_fu_171_p1.read().is_01())? sc_lv<46>(): (sc_bigint<46>(sext_cast_reg_202.read()) + sc_biguint<46>(tmp_1_fu_171_p1.read()));
}

void blur_Mat2Array::thread_tmp_5_fu_180_p1() {
    tmp_5_fu_180_p1 = esl_sext<64,46>(tmp_4_fu_175_p2.read());
}

void blur_Mat2Array::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_125_p2.read())) {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            } else {
                ap_NS_fsm = ap_ST_st3_fsm_2;
            }
            break;
        case 4 : 
            if (!esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_m_axi_fb_AWREADY.read())) {
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_3;
            } else {
                ap_NS_fsm = ap_ST_st3_fsm_2;
            }
            break;
        case 8 : 
            if ((!(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && !((ap_sig_bdd_127.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond_reg_220_pp0_it1.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_m_axi_fb_WREADY.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()))) && !esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && !((ap_sig_bdd_127.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond_reg_220_pp0_it1.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_m_axi_fb_WREADY.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()))) && !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_190_p2.read()) && !esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_3;
            } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
  !((ap_sig_bdd_127.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond_reg_220_pp0_it1.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_m_axi_fb_WREADY.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()))) && 
  !esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
  !((ap_sig_bdd_127.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond_reg_220_pp0_it1.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_m_axi_fb_WREADY.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()))) && 
  !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_190_p2.read()) && 
  !esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
                ap_NS_fsm = ap_ST_st7_fsm_4;
            } else {
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_3;
            }
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_st8_fsm_5;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_st9_fsm_6;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_st10_fsm_7;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_st11_fsm_8;
            break;
        case 256 : 
            if (!esl_seteq<1,1,1>(m_axi_fb_BVALID.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st11_fsm_8;
            }
            break;
        default : 
            ap_NS_fsm = "XXXXXXXXX";
            break;
    }
}

}

